import type { Sentence } from '../../types';

export const CAFE_SENTENCES: readonly Sentence[] = [
  {
    id: 'l1_cafe_001',
    jp: 'すみません、アイスコーヒーをください。',
    kana: 'すみません、アイスコーヒーをください。',
    kr: '저기요, 아이스커피 주세요.',
    roman: 'Sumimasen, aisu koohii wo kudasai.',
    chunks: [
      { jp: 'すみません', kana: 'すみません', kr: '저기요', roman: 'sumimasen' },
      {
        jp: 'アイスコーヒーを',
        kana: 'アイスコーヒーを',
        kr: '아이스커피를',
        roman: 'aisu koohii wo',
      },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: 'コーヒー', kana: 'コーヒー', kr: '커피', icon: '☕' },
      { jp: 'ください', kana: 'ください', kr: '주세요', icon: '🙏' },
    ],
    categoryId: 'l1_cafe',
    level: 1,
    order: 1,
    tip: 'ください는 "~해주세요"의 가장 기본적인 표현이에요!',
  },
  {
    id: 'l1_cafe_002',
    jp: 'ホットコーヒーはありますか？',
    kana: 'ホットコーヒーはありますか？',
    kr: '따뜻한 커피 있나요?',
    roman: 'Hotto koohii wa arimasu ka?',
    chunks: [
      {
        jp: 'ホットコーヒーは',
        kana: 'ホットコーヒーは',
        kr: '따뜻한 커피는',
        roman: 'hotto koohii wa',
      },
      { jp: 'ありますか', kana: 'ありますか', kr: '있나요', roman: 'arimasu ka' },
    ],
    keywords: [
      { jp: 'ホット', kana: 'ホット', kr: '따뜻한', icon: '🔥' },
      { jp: 'あります', kana: 'あります', kr: '있습니다', icon: '✓' },
    ],
    categoryId: 'l1_cafe',
    level: 1,
    order: 2,
    tip: '~ありますか?는 "~있나요?"로 물건의 유무를 물을 때 사용해요.',
  },
  {
    id: 'l1_cafe_003',
    jp: 'お会計お願いします。',
    kana: 'おかいけいおねがいします。',
    kr: '계산해 주세요.',
    roman: 'Okaikei onegaishimasu.',
    chunks: [
      { jp: 'お会計', kana: 'おかいけい', kr: '계산', roman: 'okaikei' },
      {
        jp: 'お願いします',
        kana: 'おねがいします',
        kr: '부탁합니다',
        roman: 'onegaishimasu',
      },
    ],
    keywords: [
      { jp: '会計', kana: 'かいけい', kr: '계산', icon: '💰' },
      { jp: 'お願いします', kana: 'おねがいします', kr: '부탁합니다', icon: '🙏' },
    ],
    categoryId: 'l1_cafe',
    level: 1,
    order: 3,
    tip: 'お願いします는 ください보다 더 정중한 표현이에요.',
  },
  {
    id: 'l1_cafe_004',
    jp: 'メニューを見せてください。',
    kana: 'メニューをみせてください。',
    kr: '메뉴판 좀 보여주세요.',
    roman: 'Menyuu wo misete kudasai.',
    chunks: [
      { jp: 'メニューを', kana: 'メニューを', kr: '메뉴판을', roman: 'menyuu wo' },
      { jp: '見せて', kana: 'みせて', kr: '보여', roman: 'misete' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: 'メニュー', kana: 'メニュー', kr: '메뉴', icon: '📋' },
      { jp: '見せる', kana: 'みせる', kr: '보여주다', icon: '👀' },
    ],
    categoryId: 'l1_cafe',
    level: 1,
    order: 4,
    tip: '~て ください는 동사의 て형 + ください로 부탁하는 표현이에요.',
  },
  {
    id: 'l1_cafe_005',
    jp: '席はありますか？',
    kana: 'せきはありますか？',
    kr: '자리 있나요?',
    roman: 'Seki wa arimasu ka?',
    chunks: [
      { jp: '席は', kana: 'せきは', kr: '자리는', roman: 'seki wa' },
      { jp: 'ありますか', kana: 'ありますか', kr: '있나요', roman: 'arimasu ka' },
    ],
    keywords: [
      { jp: '席', kana: 'せき', kr: '자리', icon: '💺' },
      { jp: 'あります', kana: 'あります', kr: '있습니다', icon: '✓' },
    ],
    categoryId: 'l1_cafe',
    level: 1,
    order: 5,
    tip: '카페나 식당에 들어가서 자리를 확인할 때 사용해요.',
  },
  {
    id: 'l1_cafe_006',
    jp: 'ケーキも一つください。',
    kana: 'ケーキもひとつください。',
    kr: '케이크도 하나 주세요.',
    roman: 'Keeki mo hitotsu kudasai.',
    chunks: [
      { jp: 'ケーキも', kana: 'ケーキも', kr: '케이크도', roman: 'keeki mo' },
      { jp: '一つ', kana: 'ひとつ', kr: '하나', roman: 'hitotsu' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: 'ケーキ', kana: 'ケーキ', kr: '케이크', icon: '🍰' },
      { jp: '一つ', kana: 'ひとつ', kr: '하나', icon: '1️⃣' },
    ],
    categoryId: 'l1_cafe',
    level: 1,
    order: 6,
    tip: '~も는 "~도"라는 뜻으로 추가 주문할 때 사용해요.',
  },
  {
    id: 'l1_cafe_007',
    jp: 'Mサイズでお願いします。',
    kana: 'エムサイズでおねがいします。',
    kr: 'M사이즈로 부탁드려요.',
    roman: 'Emu saizu de onegaishimasu.',
    chunks: [
      { jp: 'Mサイズで', kana: 'エムサイズで', kr: 'M사이즈로', roman: 'emu saizu de' },
      { jp: 'お願いします', kana: 'おねがいします', kr: '부탁드려요', roman: 'onegaishimasu' },
    ],
    keywords: [
      { jp: 'サイズ', kana: 'サイズ', kr: '사이즈', icon: '📏' },
      { jp: 'お願いします', kana: 'おねがいします', kr: '부탁합니다', icon: '🙏' },
    ],
    categoryId: 'l1_cafe',
    level: 1,
    order: 7,
    tip: '~で는 "~로"라는 뜻으로 선택할 때 사용해요.',
  },
  {
    id: 'l1_cafe_008',
    jp: '持ち帰りでお願いします。',
    kana: 'もちかえりでおねがいします。',
    kr: '포장해 주세요.',
    roman: 'Mochikaeri de onegaishimasu.',
    chunks: [
      { jp: '持ち帰りで', kana: 'もちかえりで', kr: '포장으로', roman: 'mochikaeri de' },
      { jp: 'お願いします', kana: 'おねがいします', kr: '부탁드려요', roman: 'onegaishimasu' },
    ],
    keywords: [
      { jp: '持ち帰り', kana: 'もちかえり', kr: '포장', icon: '🥡' },
      { jp: '店内', kana: 'てんない', kr: '매장', icon: '🏠' },
    ],
    categoryId: 'l1_cafe',
    level: 1,
    order: 8,
    tip: '店内(てんない)で는 "매장에서", 持ち帰りで는 "포장으로"예요.',
  },
  {
    id: 'l1_cafe_009',
    jp: 'シロップは少なめでお願いします。',
    kana: 'シロップはすくなめでおねがいします。',
    kr: '시럽은 조금만 넣어주세요.',
    roman: 'Shiroppu wa sukuname de onegaishimasu.',
    chunks: [
      { jp: 'シロップは', kana: 'シロップは', kr: '시럽은', roman: 'shiroppu wa' },
      { jp: '少なめで', kana: 'すくなめで', kr: '적게', roman: 'sukuname de' },
      { jp: 'お願いします', kana: 'おねがいします', kr: '부탁드려요', roman: 'onegaishimasu' },
    ],
    keywords: [
      { jp: 'シロップ', kana: 'シロップ', kr: '시럽', icon: '🍯' },
      { jp: '少なめ', kana: 'すくなめ', kr: '적게', icon: '⬇️' },
    ],
    categoryId: 'l1_cafe',
    level: 1,
    order: 9,
    tip: '~め는 정도를 나타내요. 多め(おおめ, 많이), 少なめ(적게)',
  },
  {
    id: 'l1_cafe_010',
    jp: 'Wi-Fiのパスワードを教えてください。',
    kana: 'ワイファイのパスワードをおしえてください。',
    kr: '와이파이 비밀번호 알려주세요.',
    roman: 'Waifai no pasuwaado wo oshiete kudasai.',
    chunks: [
      { jp: 'Wi-Fiの', kana: 'ワイファイの', kr: '와이파이의', roman: 'waifai no' },
      { jp: 'パスワードを', kana: 'パスワードを', kr: '비밀번호를', roman: 'pasuwaado wo' },
      { jp: '教えて', kana: 'おしえて', kr: '알려', roman: 'oshiete' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: 'パスワード', kana: 'パスワード', kr: '비밀번호', icon: '🔑' },
      { jp: '教える', kana: 'おしえる', kr: '알려주다', icon: '💡' },
    ],
    categoryId: 'l1_cafe',
    level: 1,
    order: 10,
    tip: '카페에서 와이파이 쓸 때 꼭 필요한 표현이에요!',
  },
] as const;
