import type { Sentence } from '../../types';

export const EMERGENCY_SENTENCES: readonly Sentence[] = [
  {
    id: 'l1_emergency_001',
    jp: '助けてください！',
    kana: 'たすけてください！',
    kr: '도와주세요!',
    roman: 'Tasukete kudasai!',
    chunks: [
      { jp: '助けて', kana: 'たすけて', kr: '도와', roman: 'tasukete' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: '助ける', kana: 'たすける', kr: '돕다', icon: '🆘' },
      { jp: '助けて', kana: 'たすけて', kr: '도와줘', icon: '🙋' },
    ],
    categoryId: 'l1_emergency',
    level: 1,
    order: 1,
    tip: '긴급할 때는 助けて! 만으로도 충분해요.',
  },
  {
    id: 'l1_emergency_002',
    jp: '道に迷いました。',
    kana: 'みちにまよいました。',
    kr: '길을 잃었어요.',
    roman: 'Michi ni mayoimashita.',
    chunks: [
      { jp: '道に', kana: 'みちに', kr: '길을', roman: 'michi ni' },
      { jp: '迷いました', kana: 'まよいました', kr: '잃었어요', roman: 'mayoimashita' },
    ],
    keywords: [
      { jp: '道', kana: 'みち', kr: '길', icon: '🛤️' },
      { jp: '迷う', kana: 'まよう', kr: '헤매다', icon: '😵' },
    ],
    categoryId: 'l1_emergency',
    level: 1,
    order: 2,
    tip: '길을 물을 때 이 표현으로 시작하면 친절하게 알려줘요.',
  },
  {
    id: 'l1_emergency_003',
    jp: '財布をなくしました。',
    kana: 'さいふをなくしました。',
    kr: '지갑을 잃어버렸어요.',
    roman: 'Saifu wo nakushimashita.',
    chunks: [
      { jp: '財布を', kana: 'さいふを', kr: '지갑을', roman: 'saifu wo' },
      { jp: 'なくしました', kana: 'なくしました', kr: '잃어버렸어요', roman: 'nakushimashita' },
    ],
    keywords: [
      { jp: '財布', kana: 'さいふ', kr: '지갑', icon: '👛' },
      { jp: 'なくす', kana: 'なくす', kr: '잃어버리다', icon: '❌' },
    ],
    categoryId: 'l1_emergency',
    level: 1,
    order: 3,
    tip: 'パスポート(여권), 携帯(휴대폰)도 같은 패턴으로 말해요.',
  },
  {
    id: 'l1_emergency_004',
    jp: '警察を呼んでください。',
    kana: 'けいさつをよんでください。',
    kr: '경찰을 불러주세요.',
    roman: 'Keisatsu wo yonde kudasai.',
    chunks: [
      { jp: '警察を', kana: 'けいさつを', kr: '경찰을', roman: 'keisatsu wo' },
      { jp: '呼んで', kana: 'よんで', kr: '불러', roman: 'yonde' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: '警察', kana: 'けいさつ', kr: '경찰', icon: '👮' },
      { jp: '呼ぶ', kana: 'よぶ', kr: '부르다', icon: '📞' },
    ],
    categoryId: 'l1_emergency',
    level: 1,
    order: 4,
    tip: '일본 경찰 신고는 110번이에요.',
  },
  {
    id: 'l1_emergency_005',
    jp: '救急車を呼んでください。',
    kana: 'きゅうきゅうしゃをよんでください。',
    kr: '구급차를 불러주세요.',
    roman: 'Kyuukyuusha wo yonde kudasai.',
    chunks: [
      { jp: '救急車を', kana: 'きゅうきゅうしゃを', kr: '구급차를', roman: 'kyuukyuusha wo' },
      { jp: '呼んで', kana: 'よんで', kr: '불러', roman: 'yonde' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: '救急車', kana: 'きゅうきゅうしゃ', kr: '구급차', icon: '🚑' },
      { jp: '病院', kana: 'びょういん', kr: '병원', icon: '🏥' },
    ],
    categoryId: 'l1_emergency',
    level: 1,
    order: 5,
    tip: '일본 구급/소방 신고는 119번이에요.',
  },
  {
    id: 'l1_emergency_006',
    jp: '気分が悪いです。',
    kana: 'きぶんがわるいです。',
    kr: '몸이 안 좋아요.',
    roman: 'Kibun ga warui desu.',
    chunks: [
      { jp: '気分が', kana: 'きぶんが', kr: '기분이', roman: 'kibun ga' },
      { jp: '悪いです', kana: 'わるいです', kr: '안 좋아요', roman: 'warui desu' },
    ],
    keywords: [
      { jp: '気分', kana: 'きぶん', kr: '기분/컨디션', icon: '😰' },
      { jp: '悪い', kana: 'わるい', kr: '나쁘다', icon: '👎' },
    ],
    categoryId: 'l1_emergency',
    level: 1,
    order: 6,
    tip: '気分が悪い는 속이 안 좋거나 어지러울 때 사용해요.',
  },
  {
    id: 'l1_emergency_007',
    jp: '頭が痛いです。',
    kana: 'あたまがいたいです。',
    kr: '머리가 아파요.',
    roman: 'Atama ga itai desu.',
    chunks: [
      { jp: '頭が', kana: 'あたまが', kr: '머리가', roman: 'atama ga' },
      { jp: '痛いです', kana: 'いたいです', kr: '아파요', roman: 'itai desu' },
    ],
    keywords: [
      { jp: '頭', kana: 'あたま', kr: '머리', icon: '🤕' },
      { jp: '痛い', kana: 'いたい', kr: '아프다', icon: '💊' },
    ],
    categoryId: 'l1_emergency',
    level: 1,
    order: 7,
    tip: 'お腹(おなか, 배), 歯(は, 이)도 같은 패턴으로 말해요.',
  },
  {
    id: 'l1_emergency_008',
    jp: '薬局はどこですか？',
    kana: 'やっきょくはどこですか？',
    kr: '약국은 어디인가요?',
    roman: 'Yakkyoku wa doko desu ka?',
    chunks: [
      { jp: '薬局は', kana: 'やっきょくは', kr: '약국은', roman: 'yakkyoku wa' },
      { jp: 'どこですか', kana: 'どこですか', kr: '어디인가요', roman: 'doko desu ka' },
    ],
    keywords: [
      { jp: '薬局', kana: 'やっきょく', kr: '약국', icon: '💊' },
      { jp: '薬', kana: 'くすり', kr: '약', icon: '💉' },
    ],
    categoryId: 'l1_emergency',
    level: 1,
    order: 8,
    tip: '일본 약국은 ドラッグストア라고도 해요.',
  },
  {
    id: 'l1_emergency_009',
    jp: '日本語がわかりません。',
    kana: 'にほんごがわかりません。',
    kr: '일본어를 모르겠어요.',
    roman: 'Nihongo ga wakarimasen.',
    chunks: [
      { jp: '日本語が', kana: 'にほんごが', kr: '일본어를', roman: 'nihongo ga' },
      { jp: 'わかりません', kana: 'わかりません', kr: '모르겠어요', roman: 'wakarimasen' },
    ],
    keywords: [
      { jp: '日本語', kana: 'にほんご', kr: '일본어', icon: '🇯🇵' },
      { jp: 'わかる', kana: 'わかる', kr: '알다', icon: '💡' },
    ],
    categoryId: 'l1_emergency',
    level: 1,
    order: 9,
    tip: '상대방이 빠르게 말할 때 이 표현을 사용하세요.',
  },
  {
    id: 'l1_emergency_010',
    jp: '英語を話せる人はいますか？',
    kana: 'えいごをはなせるひとはいますか？',
    kr: '영어 할 수 있는 분 계신가요?',
    roman: 'Eigo wo hanaseru hito wa imasu ka?',
    chunks: [
      { jp: '英語を', kana: 'えいごを', kr: '영어를', roman: 'eigo wo' },
      { jp: '話せる', kana: 'はなせる', kr: '말할 수 있는', roman: 'hanaseru' },
      { jp: '人は', kana: 'ひとは', kr: '사람은', roman: 'hito wa' },
      { jp: 'いますか', kana: 'いますか', kr: '있나요', roman: 'imasu ka' },
    ],
    keywords: [
      { jp: '英語', kana: 'えいご', kr: '영어', icon: '🇺🇸' },
      { jp: '話せる', kana: 'はなせる', kr: '말할 수 있다', icon: '🗣️' },
    ],
    categoryId: 'l1_emergency',
    level: 1,
    order: 10,
    tip: '韓国語(かんこくご)로 바꾸면 한국어 가능자를 찾을 수 있어요.',
  },
] as const;
