import type { Sentence } from '../../types';

export const HOTEL_SENTENCES: readonly Sentence[] = [
  {
    id: 'l1_hotel_001',
    jp: 'チェックインお願いします。',
    kana: 'チェックインおねがいします。',
    kr: '체크인 부탁드립니다.',
    roman: 'Chekkuin onegaishimasu.',
    chunks: [
      { jp: 'チェックイン', kana: 'チェックイン', kr: '체크인', roman: 'chekkuin' },
      { jp: 'お願いします', kana: 'おねがいします', kr: '부탁드립니다', roman: 'onegaishimasu' },
    ],
    keywords: [
      { jp: 'チェックイン', kana: 'チェックイン', kr: '체크인', icon: '🔑' },
      { jp: 'お願いします', kana: 'おねがいします', kr: '부탁합니다', icon: '🙏' },
    ],
    categoryId: 'l1_hotel',
    level: 1,
    order: 1,
    tip: '호텔 프론트에서 가장 먼저 하는 말이에요.',
  },
  {
    id: 'l1_hotel_002',
    jp: '予約した田中です。',
    kana: 'よやくしたたなかです。',
    kr: '예약한 다나카입니다.',
    roman: 'Yoyaku shita Tanaka desu.',
    chunks: [
      { jp: '予約した', kana: 'よやくした', kr: '예약한', roman: 'yoyaku shita' },
      { jp: '田中です', kana: 'たなかです', kr: '다나카입니다', roman: 'Tanaka desu' },
    ],
    keywords: [
      { jp: '予約', kana: 'よやく', kr: '예약', icon: '📅' },
      { jp: '~した', kana: '~した', kr: '~한', icon: '✓' },
    ],
    categoryId: 'l1_hotel',
    level: 1,
    order: 2,
    tip: '이름 부분에 자신의 이름을 넣어 사용하세요.',
  },
  {
    id: 'l1_hotel_003',
    jp: 'チェックアウトは何時ですか？',
    kana: 'チェックアウトはなんじですか？',
    kr: '체크아웃은 몇 시인가요?',
    roman: 'Chekkuauto wa nanji desu ka?',
    chunks: [
      { jp: 'チェックアウトは', kana: 'チェックアウトは', kr: '체크아웃은', roman: 'chekkuauto wa' },
      { jp: '何時ですか', kana: 'なんじですか', kr: '몇 시인가요', roman: 'nanji desu ka' },
    ],
    keywords: [
      { jp: 'チェックアウト', kana: 'チェックアウト', kr: '체크아웃', icon: '🚪' },
      { jp: '何時', kana: 'なんじ', kr: '몇 시', icon: '🕐' },
    ],
    categoryId: 'l1_hotel',
    level: 1,
    order: 3,
    tip: '보통 일본 호텔은 10시나 11시가 체크아웃 시간이에요.',
  },
  {
    id: 'l1_hotel_004',
    jp: '荷物を預かってもらえますか？',
    kana: 'にもつをあずかってもらえますか？',
    kr: '짐을 맡아주실 수 있나요?',
    roman: 'Nimotsu wo azukatte moraemasu ka?',
    chunks: [
      { jp: '荷物を', kana: 'にもつを', kr: '짐을', roman: 'nimotsu wo' },
      { jp: '預かって', kana: 'あずかって', kr: '맡아', roman: 'azukatte' },
      { jp: 'もらえますか', kana: 'もらえますか', kr: '주실 수 있나요', roman: 'moraemasu ka' },
    ],
    keywords: [
      { jp: '荷物', kana: 'にもつ', kr: '짐', icon: '🧳' },
      { jp: '預かる', kana: 'あずかる', kr: '맡기다', icon: '🔐' },
    ],
    categoryId: 'l1_hotel',
    level: 1,
    order: 4,
    tip: '체크인 전이나 체크아웃 후 짐을 맡길 때 사용해요.',
  },
  {
    id: 'l1_hotel_005',
    jp: 'Wi-Fiのパスワードは何ですか？',
    kana: 'ワイファイのパスワードはなんですか？',
    kr: '와이파이 비밀번호가 뭔가요?',
    roman: 'Waifai no pasuwaado wa nan desu ka?',
    chunks: [
      { jp: 'Wi-Fiの', kana: 'ワイファイの', kr: '와이파이의', roman: 'waifai no' },
      { jp: 'パスワードは', kana: 'パスワードは', kr: '비밀번호는', roman: 'pasuwaado wa' },
      { jp: '何ですか', kana: 'なんですか', kr: '뭔가요', roman: 'nan desu ka' },
    ],
    keywords: [
      { jp: 'パスワード', kana: 'パスワード', kr: '비밀번호', icon: '🔑' },
      { jp: '何', kana: 'なに/なん', kr: '무엇', icon: '❓' },
    ],
    categoryId: 'l1_hotel',
    level: 1,
    order: 5,
    tip: '호텔 로비나 객실에서 와이파이 연결할 때 필요해요.',
  },
  {
    id: 'l1_hotel_006',
    jp: 'タオルをもう一枚ください。',
    kana: 'タオルをもういちまいください。',
    kr: '수건 한 장 더 주세요.',
    roman: 'Taoru wo mou ichimai kudasai.',
    chunks: [
      { jp: 'タオルを', kana: 'タオルを', kr: '수건을', roman: 'taoru wo' },
      { jp: 'もう一枚', kana: 'もういちまい', kr: '한 장 더', roman: 'mou ichimai' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: 'タオル', kana: 'タオル', kr: '수건', icon: '🛁' },
      { jp: 'もう一枚', kana: 'もういちまい', kr: '한 장 더', icon: '➕' },
    ],
    categoryId: 'l1_hotel',
    level: 1,
    order: 6,
    tip: 'もう~는 "더"라는 뜻으로 추가 요청할 때 사용해요.',
  },
  {
    id: 'l1_hotel_007',
    jp: 'エアコンが動きません。',
    kana: 'エアコンがうごきません。',
    kr: '에어컨이 작동하지 않아요.',
    roman: 'Eakon ga ugokimasen.',
    chunks: [
      { jp: 'エアコンが', kana: 'エアコンが', kr: '에어컨이', roman: 'eakon ga' },
      { jp: '動きません', kana: 'うごきません', kr: '작동하지 않아요', roman: 'ugokimasen' },
    ],
    keywords: [
      { jp: 'エアコン', kana: 'エアコン', kr: '에어컨', icon: '❄️' },
      { jp: '動く', kana: 'うごく', kr: '움직이다', icon: '⚙️' },
    ],
    categoryId: 'l1_hotel',
    level: 1,
    order: 7,
    tip: '시설 고장을 신고할 때 사용하는 패턴이에요.',
  },
  {
    id: 'l1_hotel_008',
    jp: '朝食は何時からですか？',
    kana: 'ちょうしょくはなんじからですか？',
    kr: '조식은 몇 시부터인가요?',
    roman: 'Choushoku wa nanji kara desu ka?',
    chunks: [
      { jp: '朝食は', kana: 'ちょうしょくは', kr: '조식은', roman: 'choushoku wa' },
      { jp: '何時から', kana: 'なんじから', kr: '몇 시부터', roman: 'nanji kara' },
      { jp: 'ですか', kana: 'ですか', kr: '인가요', roman: 'desu ka' },
    ],
    keywords: [
      { jp: '朝食', kana: 'ちょうしょく', kr: '조식', icon: '🍳' },
      { jp: '~から', kana: '~から', kr: '~부터', icon: '▶️' },
    ],
    categoryId: 'l1_hotel',
    level: 1,
    order: 8,
    tip: '~から~まで는 "~부터 ~까지"라는 뜻이에요.',
  },
  {
    id: 'l1_hotel_009',
    jp: '部屋を変えてもらえますか？',
    kana: 'へやをかえてもらえますか？',
    kr: '방을 바꿔주실 수 있나요?',
    roman: 'Heya wo kaete moraemasu ka?',
    chunks: [
      { jp: '部屋を', kana: 'へやを', kr: '방을', roman: 'heya wo' },
      { jp: '変えて', kana: 'かえて', kr: '바꿔', roman: 'kaete' },
      { jp: 'もらえますか', kana: 'もらえますか', kr: '주실 수 있나요', roman: 'moraemasu ka' },
    ],
    keywords: [
      { jp: '部屋', kana: 'へや', kr: '방', icon: '🛏️' },
      { jp: '変える', kana: 'かえる', kr: '바꾸다', icon: '🔄' },
    ],
    categoryId: 'l1_hotel',
    level: 1,
    order: 9,
    tip: '방에 문제가 있을 때 정중하게 요청하는 표현이에요.',
  },
  {
    id: 'l1_hotel_010',
    jp: '領収書をお願いします。',
    kana: 'りょうしゅうしょをおねがいします。',
    kr: '영수증 부탁드립니다.',
    roman: 'Ryoushuusho wo onegaishimasu.',
    chunks: [
      { jp: '領収書を', kana: 'りょうしゅうしょを', kr: '영수증을', roman: 'ryoushuusho wo' },
      { jp: 'お願いします', kana: 'おねがいします', kr: '부탁드립니다', roman: 'onegaishimasu' },
    ],
    keywords: [
      { jp: '領収書', kana: 'りょうしゅうしょ', kr: '영수증', icon: '🧾' },
      { jp: 'レシート', kana: 'レシート', kr: '영수증(간이)', icon: '📃' },
    ],
    categoryId: 'l1_hotel',
    level: 1,
    order: 10,
    tip: '領収書는 정식 영수증, レシート는 간이 영수증이에요.',
  },
] as const;
