import type { Sentence } from '../../types';

export const SHOPPING_SENTENCES: readonly Sentence[] = [
  {
    id: 'l1_shopping_001',
    jp: 'これはいくらですか？',
    kana: 'これはいくらですか？',
    kr: '이거 얼마인가요?',
    roman: 'Kore wa ikura desu ka?',
    chunks: [
      { jp: 'これは', kana: 'これは', kr: '이것은', roman: 'kore wa' },
      { jp: 'いくらですか', kana: 'いくらですか', kr: '얼마인가요', roman: 'ikura desu ka' },
    ],
    keywords: [
      { jp: 'これ', kana: 'これ', kr: '이것', icon: '👆' },
      { jp: 'いくら', kana: 'いくら', kr: '얼마', icon: '💴' },
    ],
    categoryId: 'l1_shopping',
    level: 1,
    order: 1,
    tip: '가격을 물을 때 가장 기본적인 표현이에요.',
  },
  {
    id: 'l1_shopping_002',
    jp: 'あれを見せてください。',
    kana: 'あれをみせてください。',
    kr: '저거 좀 보여주세요.',
    roman: 'Are wo misete kudasai.',
    chunks: [
      { jp: 'あれを', kana: 'あれを', kr: '저것을', roman: 'are wo' },
      { jp: '見せて', kana: 'みせて', kr: '보여', roman: 'misete' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: 'あれ', kana: 'あれ', kr: '저것', icon: '👉' },
      { jp: '見せる', kana: 'みせる', kr: '보여주다', icon: '👀' },
    ],
    categoryId: 'l1_shopping',
    level: 1,
    order: 2,
    tip: 'これ(이것), それ(그것), あれ(저것)를 구분해서 사용해요.',
  },
  {
    id: 'l1_shopping_003',
    jp: 'この服がほしいです。',
    kana: 'このふくがほしいです。',
    kr: '이 옷이 갖고 싶어요.',
    roman: 'Kono fuku ga hoshii desu.',
    chunks: [
      { jp: 'この服が', kana: 'このふくが', kr: '이 옷이', roman: 'kono fuku ga' },
      { jp: 'ほしいです', kana: 'ほしいです', kr: '갖고 싶어요', roman: 'hoshii desu' },
    ],
    keywords: [
      { jp: '服', kana: 'ふく', kr: '옷', icon: '👕' },
      { jp: 'ほしい', kana: 'ほしい', kr: '갖고 싶다', icon: '🛒' },
    ],
    categoryId: 'l1_shopping',
    level: 1,
    order: 3,
    tip: '~がほしい는 물건을 갖고 싶을 때 사용해요.',
  },
  {
    id: 'l1_shopping_004',
    jp: '他のサイズはありますか？',
    kana: 'ほかのサイズはありますか？',
    kr: '다른 사이즈 있나요?',
    roman: 'Hoka no saizu wa arimasu ka?',
    chunks: [
      { jp: '他の', kana: 'ほかの', kr: '다른', roman: 'hoka no' },
      { jp: 'サイズは', kana: 'サイズは', kr: '사이즈는', roman: 'saizu wa' },
      { jp: 'ありますか', kana: 'ありますか', kr: '있나요', roman: 'arimasu ka' },
    ],
    keywords: [
      { jp: '他', kana: 'ほか', kr: '다른', icon: '🔄' },
      { jp: 'サイズ', kana: 'サイズ', kr: '사이즈', icon: '📏' },
    ],
    categoryId: 'l1_shopping',
    level: 1,
    order: 4,
    tip: '他の(ほかの)는 "다른"이라는 뜻이에요.',
  },
  {
    id: 'l1_shopping_005',
    jp: '違う色はありますか？',
    kana: 'ちがういろはありますか？',
    kr: '다른 색깔 있나요?',
    roman: 'Chigau iro wa arimasu ka?',
    chunks: [
      { jp: '違う', kana: 'ちがう', kr: '다른', roman: 'chigau' },
      { jp: '色は', kana: 'いろは', kr: '색깔은', roman: 'iro wa' },
      { jp: 'ありますか', kana: 'ありますか', kr: '있나요', roman: 'arimasu ka' },
    ],
    keywords: [
      { jp: '違う', kana: 'ちがう', kr: '다르다', icon: '🔀' },
      { jp: '色', kana: 'いろ', kr: '색깔', icon: '🎨' },
    ],
    categoryId: 'l1_shopping',
    level: 1,
    order: 5,
    tip: '違う(ちがう)는 "다르다"라는 뜻이에요.',
  },
  {
    id: 'l1_shopping_006',
    jp: '少し安くなりますか？',
    kana: 'すこしやすくなりますか？',
    kr: '조금 싸게 해주실 수 있나요?',
    roman: 'Sukoshi yasuku narimasu ka?',
    chunks: [
      { jp: '少し', kana: 'すこし', kr: '조금', roman: 'sukoshi' },
      { jp: '安く', kana: 'やすく', kr: '싸게', roman: 'yasuku' },
      { jp: 'なりますか', kana: 'なりますか', kr: '되나요', roman: 'narimasu ka' },
    ],
    keywords: [
      { jp: '少し', kana: 'すこし', kr: '조금', icon: '🤏' },
      { jp: '安い', kana: 'やすい', kr: '싸다', icon: '💰' },
    ],
    categoryId: 'l1_shopping',
    level: 1,
    order: 6,
    tip: '일본에서는 흥정이 흔하지 않지만, 가전매장 등에서는 가능해요.',
  },
  {
    id: 'l1_shopping_007',
    jp: '試着室はどこですか？',
    kana: 'しちゃくしつはどこですか？',
    kr: '탈의실은 어디인가요?',
    roman: 'Shichakushitsu wa doko desu ka?',
    chunks: [
      { jp: '試着室は', kana: 'しちゃくしつは', kr: '탈의실은', roman: 'shichakushitsu wa' },
      { jp: 'どこですか', kana: 'どこですか', kr: '어디인가요', roman: 'doko desu ka' },
    ],
    keywords: [
      { jp: '試着室', kana: 'しちゃくしつ', kr: '탈의실', icon: '🚪' },
      { jp: '試着', kana: 'しちゃく', kr: '입어보기', icon: '👗' },
    ],
    categoryId: 'l1_shopping',
    level: 1,
    order: 7,
    tip: '試着してもいいですか? (입어봐도 될까요?)도 함께 기억해요.',
  },
  {
    id: 'l1_shopping_008',
    jp: 'クレジットカードで払えますか？',
    kana: 'クレジットカードではらえますか？',
    kr: '신용카드로 계산할 수 있나요?',
    roman: 'Kurejitto kaado de haraemasu ka?',
    chunks: [
      { jp: 'クレジットカードで', kana: 'クレジットカードで', kr: '신용카드로', roman: 'kurejitto kaado de' },
      { jp: '払えますか', kana: 'はらえますか', kr: '계산할 수 있나요', roman: 'haraemasu ka' },
    ],
    keywords: [
      { jp: 'クレジットカード', kana: 'クレジットカード', kr: '신용카드', icon: '💳' },
      { jp: '払う', kana: 'はらう', kr: '지불하다', icon: '💵' },
    ],
    categoryId: 'l1_shopping',
    level: 1,
    order: 8,
    tip: '払えますか는 "지불할 수 있나요?"로 가능 여부를 물어요.',
  },
  {
    id: 'l1_shopping_009',
    jp: '免税できますか？',
    kana: 'めんぜいできますか？',
    kr: '면세 되나요?',
    roman: 'Menzei dekimasu ka?',
    chunks: [
      { jp: '免税', kana: 'めんぜい', kr: '면세', roman: 'menzei' },
      { jp: 'できますか', kana: 'できますか', kr: '되나요', roman: 'dekimasu ka' },
    ],
    keywords: [
      { jp: '免税', kana: 'めんぜい', kr: '면세', icon: '🛃' },
      { jp: 'できる', kana: 'できる', kr: '할 수 있다', icon: '✅' },
    ],
    categoryId: 'l1_shopping',
    level: 1,
    order: 9,
    tip: '5000엔 이상 구매 시 Tax Free 가능한 매장이 많아요.',
  },
  {
    id: 'l1_shopping_010',
    jp: '袋をもらえますか？',
    kana: 'ふくろをもらえますか？',
    kr: '봉투 받을 수 있나요?',
    roman: 'Fukuro wo moraemasu ka?',
    chunks: [
      { jp: '袋を', kana: 'ふくろを', kr: '봉투를', roman: 'fukuro wo' },
      { jp: 'もらえますか', kana: 'もらえますか', kr: '받을 수 있나요', roman: 'moraemasu ka' },
    ],
    keywords: [
      { jp: '袋', kana: 'ふくろ', kr: '봉투', icon: '🛍️' },
      { jp: 'もらう', kana: 'もらう', kr: '받다', icon: '🤲' },
    ],
    categoryId: 'l1_shopping',
    level: 1,
    order: 10,
    tip: '일본은 비닐봉투가 유료(3~5엔)인 곳이 많아요.',
  },
] as const;
