import type { Sentence } from '../../types';

export const TOURIST_SENTENCES: readonly Sentence[] = [
  {
    id: 'l1_tourist_001',
    jp: '写真を撮ってもらえますか？',
    kana: 'しゃしんをとってもらえますか？',
    kr: '사진 찍어주실 수 있나요?',
    roman: 'Shashin wo totte moraemasu ka?',
    chunks: [
      { jp: '写真を', kana: 'しゃしんを', kr: '사진을', roman: 'shashin wo' },
      { jp: '撮って', kana: 'とって', kr: '찍어', roman: 'totte' },
      { jp: 'もらえますか', kana: 'もらえますか', kr: '주실 수 있나요', roman: 'moraemasu ka' },
    ],
    keywords: [
      { jp: '写真', kana: 'しゃしん', kr: '사진', icon: '📷' },
      { jp: '撮る', kana: 'とる', kr: '찍다', icon: '📸' },
    ],
    categoryId: 'l1_tourist',
    level: 1,
    order: 1,
    tip: '관광지에서 가장 많이 쓰는 표현 중 하나예요!',
  },
  {
    id: 'l1_tourist_002',
    jp: 'ここで写真を撮ってもいいですか？',
    kana: 'ここでしゃしんをとってもいいですか？',
    kr: '여기서 사진 찍어도 되나요?',
    roman: 'Koko de shashin wo totte mo ii desu ka?',
    chunks: [
      { jp: 'ここで', kana: 'ここで', kr: '여기서', roman: 'koko de' },
      { jp: '写真を撮っても', kana: 'しゃしんをとっても', kr: '사진을 찍어도', roman: 'shashin wo totte mo' },
      { jp: 'いいですか', kana: 'いいですか', kr: '되나요', roman: 'ii desu ka' },
    ],
    keywords: [
      { jp: 'ここ', kana: 'ここ', kr: '여기', icon: '📍' },
      { jp: '~てもいい', kana: '~てもいい', kr: '~해도 되다', icon: '✅' },
    ],
    categoryId: 'l1_tourist',
    level: 1,
    order: 2,
    tip: '~てもいいですか?는 허락을 구할 때 사용해요.',
  },
  {
    id: 'l1_tourist_003',
    jp: '入場料はいくらですか？',
    kana: 'にゅうじょうりょうはいくらですか？',
    kr: '입장료는 얼마인가요?',
    roman: 'Nyuujouryou wa ikura desu ka?',
    chunks: [
      { jp: '入場料は', kana: 'にゅうじょうりょうは', kr: '입장료는', roman: 'nyuujouryou wa' },
      { jp: 'いくらですか', kana: 'いくらですか', kr: '얼마인가요', roman: 'ikura desu ka' },
    ],
    keywords: [
      { jp: '入場料', kana: 'にゅうじょうりょう', kr: '입장료', icon: '🎫' },
      { jp: 'いくら', kana: 'いくら', kr: '얼마', icon: '💴' },
    ],
    categoryId: 'l1_tourist',
    level: 1,
    order: 3,
    tip: '박물관, 미술관, 관광지 입장 시 사용해요.',
  },
  {
    id: 'l1_tourist_004',
    jp: '大人二枚ください。',
    kana: 'おとなにまいください。',
    kr: '어른 두 장 주세요.',
    roman: 'Otona nimai kudasai.',
    chunks: [
      { jp: '大人', kana: 'おとな', kr: '어른', roman: 'otona' },
      { jp: '二枚', kana: 'にまい', kr: '두 장', roman: 'nimai' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: '大人', kana: 'おとな', kr: '어른', icon: '🧑' },
      { jp: '子供', kana: 'こども', kr: '어린이', icon: '👶' },
    ],
    categoryId: 'l1_tourist',
    level: 1,
    order: 4,
    tip: '子供(こども)는 어린이, 学生(がくせい)는 학생이에요.',
  },
  {
    id: 'l1_tourist_005',
    jp: 'ガイドマップはありますか？',
    kana: 'ガイドマップはありますか？',
    kr: '가이드맵 있나요?',
    roman: 'Gaido mappu wa arimasu ka?',
    chunks: [
      { jp: 'ガイドマップは', kana: 'ガイドマップは', kr: '가이드맵은', roman: 'gaido mappu wa' },
      { jp: 'ありますか', kana: 'ありますか', kr: '있나요', roman: 'arimasu ka' },
    ],
    keywords: [
      { jp: 'ガイドマップ', kana: 'ガイドマップ', kr: '가이드맵', icon: '🗺️' },
      { jp: 'パンフレット', kana: 'パンフレット', kr: '팸플릿', icon: '📄' },
    ],
    categoryId: 'l1_tourist',
    level: 1,
    order: 5,
    tip: '韓国語版(かんこくごばん)ありますか?로 한국어판을 요청할 수도 있어요.',
  },
  {
    id: 'l1_tourist_006',
    jp: '閉館時間は何時ですか？',
    kana: 'へいかんじかんはなんじですか？',
    kr: '폐관 시간은 몇 시인가요?',
    roman: 'Heikan jikan wa nanji desu ka?',
    chunks: [
      { jp: '閉館時間は', kana: 'へいかんじかんは', kr: '폐관 시간은', roman: 'heikan jikan wa' },
      { jp: '何時ですか', kana: 'なんじですか', kr: '몇 시인가요', roman: 'nanji desu ka' },
    ],
    keywords: [
      { jp: '閉館', kana: 'へいかん', kr: '폐관', icon: '🚪' },
      { jp: '開館', kana: 'かいかん', kr: '개관', icon: '🔓' },
    ],
    categoryId: 'l1_tourist',
    level: 1,
    order: 6,
    tip: '開館(かいかん)은 개관, 閉館(へいかん)은 폐관이에요.',
  },
  {
    id: 'l1_tourist_007',
    jp: 'お土産屋さんはどこですか？',
    kana: 'おみやげやさんはどこですか？',
    kr: '기념품 가게는 어디인가요?',
    roman: 'Omiyageya san wa doko desu ka?',
    chunks: [
      { jp: 'お土産屋さんは', kana: 'おみやげやさんは', kr: '기념품 가게는', roman: 'omiyageya san wa' },
      { jp: 'どこですか', kana: 'どこですか', kr: '어디인가요', roman: 'doko desu ka' },
    ],
    keywords: [
      { jp: 'お土産', kana: 'おみやげ', kr: '기념품', icon: '🎁' },
      { jp: '~屋さん', kana: '~やさん', kr: '~가게', icon: '🏪' },
    ],
    categoryId: 'l1_tourist',
    level: 1,
    order: 7,
    tip: '~屋さん(~やさん)은 "~가게"라는 뜻이에요.',
  },
  {
    id: 'l1_tourist_008',
    jp: 'ロッカーはありますか？',
    kana: 'ロッカーはありますか？',
    kr: '물품보관함 있나요?',
    roman: 'Rokkaa wa arimasu ka?',
    chunks: [
      { jp: 'ロッカーは', kana: 'ロッカーは', kr: '물품보관함은', roman: 'rokkaa wa' },
      { jp: 'ありますか', kana: 'ありますか', kr: '있나요', roman: 'arimasu ka' },
    ],
    keywords: [
      { jp: 'ロッカー', kana: 'ロッカー', kr: '물품보관함', icon: '🔐' },
      { jp: 'コインロッカー', kana: 'コインロッカー', kr: '코인락커', icon: '🪙' },
    ],
    categoryId: 'l1_tourist',
    level: 1,
    order: 8,
    tip: '일본 관광지나 역에는 코인락커가 많아요.',
  },
  {
    id: 'l1_tourist_009',
    jp: 'この近くにコンビニはありますか？',
    kana: 'このちかくにコンビニはありますか？',
    kr: '이 근처에 편의점 있나요?',
    roman: 'Kono chikaku ni konbini wa arimasu ka?',
    chunks: [
      { jp: 'この近くに', kana: 'このちかくに', kr: '이 근처에', roman: 'kono chikaku ni' },
      { jp: 'コンビニは', kana: 'コンビニは', kr: '편의점은', roman: 'konbini wa' },
      { jp: 'ありますか', kana: 'ありますか', kr: '있나요', roman: 'arimasu ka' },
    ],
    keywords: [
      { jp: '近く', kana: 'ちかく', kr: '근처', icon: '📍' },
      { jp: 'コンビニ', kana: 'コンビニ', kr: '편의점', icon: '🏪' },
    ],
    categoryId: 'l1_tourist',
    level: 1,
    order: 9,
    tip: 'この近く(このちかく)는 "이 근처"라는 뜻이에요.',
  },
  {
    id: 'l1_tourist_010',
    jp: '一番人気は何ですか？',
    kana: 'いちばんにんきはなんですか？',
    kr: '가장 인기 있는 건 뭔가요?',
    roman: 'Ichiban ninki wa nan desu ka?',
    chunks: [
      { jp: '一番', kana: 'いちばん', kr: '가장', roman: 'ichiban' },
      { jp: '人気は', kana: 'にんきは', kr: '인기는', roman: 'ninki wa' },
      { jp: '何ですか', kana: 'なんですか', kr: '뭔가요', roman: 'nan desu ka' },
    ],
    keywords: [
      { jp: '一番', kana: 'いちばん', kr: '가장', icon: '🥇' },
      { jp: '人気', kana: 'にんき', kr: '인기', icon: '⭐' },
    ],
    categoryId: 'l1_tourist',
    level: 1,
    order: 10,
    tip: '기념품이나 음식 추천받을 때 유용한 표현이에요.',
  },
] as const;
