import type { Sentence } from '../../types';

export const TRANSPORT_SENTENCES: readonly Sentence[] = [
  {
    id: 'l1_transport_001',
    jp: '東京駅はどこですか？',
    kana: 'とうきょうえきはどこですか？',
    kr: '도쿄역은 어디인가요?',
    roman: 'Toukyou eki wa doko desu ka?',
    chunks: [
      { jp: '東京駅は', kana: 'とうきょうえきは', kr: '도쿄역은', roman: 'toukyou eki wa' },
      { jp: 'どこですか', kana: 'どこですか', kr: '어디인가요', roman: 'doko desu ka' },
    ],
    keywords: [
      { jp: '駅', kana: 'えき', kr: '역', icon: '🚉' },
      { jp: 'どこ', kana: 'どこ', kr: '어디', icon: '📍' },
    ],
    categoryId: 'l1_transport',
    level: 1,
    order: 1,
    tip: '~はどこですか?는 장소를 물을 때 가장 기본적인 표현이에요.',
  },
  {
    id: 'l1_transport_002',
    jp: '渋谷に行きたいです。',
    kana: 'しぶやにいきたいです。',
    kr: '시부야에 가고 싶어요.',
    roman: 'Shibuya ni ikitai desu.',
    chunks: [
      { jp: '渋谷に', kana: 'しぶやに', kr: '시부야에', roman: 'shibuya ni' },
      { jp: '行きたい', kana: 'いきたい', kr: '가고 싶어', roman: 'ikitai' },
      { jp: 'です', kana: 'です', kr: '요', roman: 'desu' },
    ],
    keywords: [
      { jp: '行く', kana: 'いく', kr: '가다', icon: '🚶' },
      { jp: '~たい', kana: '~たい', kr: '~하고 싶다', icon: '💭' },
    ],
    categoryId: 'l1_transport',
    level: 1,
    order: 2,
    tip: '~たいです는 "~하고 싶어요"로 희망을 나타내요.',
  },
  {
    id: 'l1_transport_003',
    jp: '切符を一枚ください。',
    kana: 'きっぷをいちまいください。',
    kr: '표 한 장 주세요.',
    roman: 'Kippu wo ichimai kudasai.',
    chunks: [
      { jp: '切符を', kana: 'きっぷを', kr: '표를', roman: 'kippu wo' },
      { jp: '一枚', kana: 'いちまい', kr: '한 장', roman: 'ichimai' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: '切符', kana: 'きっぷ', kr: '표', icon: '🎫' },
      { jp: '一枚', kana: 'いちまい', kr: '한 장', icon: '1️⃣' },
    ],
    categoryId: 'l1_transport',
    level: 1,
    order: 3,
    tip: '枚(まい)는 종이처럼 얇은 것을 세는 단위예요.',
  },
  {
    id: 'l1_transport_004',
    jp: 'この電車は新宿に止まりますか？',
    kana: 'このでんしゃはしんじゅくにとまりますか？',
    kr: '이 전철은 신주쿠에 서나요?',
    roman: 'Kono densha wa Shinjuku ni tomarimasu ka?',
    chunks: [
      { jp: 'この電車は', kana: 'このでんしゃは', kr: '이 전철은', roman: 'kono densha wa' },
      { jp: '新宿に', kana: 'しんじゅくに', kr: '신주쿠에', roman: 'shinjuku ni' },
      { jp: '止まりますか', kana: 'とまりますか', kr: '서나요', roman: 'tomarimasu ka' },
    ],
    keywords: [
      { jp: '電車', kana: 'でんしゃ', kr: '전철', icon: '🚃' },
      { jp: '止まる', kana: 'とまる', kr: '서다', icon: '🛑' },
    ],
    categoryId: 'l1_transport',
    level: 1,
    order: 4,
    tip: '급행/특급 탈 때 원하는 역에 서는지 확인하는 표현이에요.',
  },
  {
    id: 'l1_transport_005',
    jp: '乗り換えはどこですか？',
    kana: 'のりかえはどこですか？',
    kr: '환승은 어디서 하나요?',
    roman: 'Norikae wa doko desu ka?',
    chunks: [
      { jp: '乗り換えは', kana: 'のりかえは', kr: '환승은', roman: 'norikae wa' },
      { jp: 'どこですか', kana: 'どこですか', kr: '어디인가요', roman: 'doko desu ka' },
    ],
    keywords: [
      { jp: '乗り換え', kana: 'のりかえ', kr: '환승', icon: '🔄' },
      { jp: 'どこ', kana: 'どこ', kr: '어디', icon: '📍' },
    ],
    categoryId: 'l1_transport',
    level: 1,
    order: 5,
    tip: '乗り換え(のりかえ)는 환승, 갈아타기라는 뜻이에요.',
  },
  {
    id: 'l1_transport_006',
    jp: 'タクシー乗り場はどこですか？',
    kana: 'タクシーのりばはどこですか？',
    kr: '택시 타는 곳은 어디인가요?',
    roman: 'Takushii noriba wa doko desu ka?',
    chunks: [
      { jp: 'タクシー', kana: 'タクシー', kr: '택시', roman: 'takushii' },
      { jp: '乗り場は', kana: 'のりばは', kr: '타는 곳은', roman: 'noriba wa' },
      { jp: 'どこですか', kana: 'どこですか', kr: '어디인가요', roman: 'doko desu ka' },
    ],
    keywords: [
      { jp: 'タクシー', kana: 'タクシー', kr: '택시', icon: '🚕' },
      { jp: '乗り場', kana: 'のりば', kr: '타는 곳', icon: '🚏' },
    ],
    categoryId: 'l1_transport',
    level: 1,
    order: 6,
    tip: '乗り場(のりば)는 버스, 택시 등을 타는 장소예요.',
  },
  {
    id: 'l1_transport_007',
    jp: 'このホテルまでお願いします。',
    kana: 'このホテルまでおねがいします。',
    kr: '이 호텔까지 부탁드려요.',
    roman: 'Kono hoteru made onegaishimasu.',
    chunks: [
      { jp: 'この', kana: 'この', kr: '이', roman: 'kono' },
      { jp: 'ホテルまで', kana: 'ホテルまで', kr: '호텔까지', roman: 'hoteru made' },
      { jp: 'お願いします', kana: 'おねがいします', kr: '부탁드려요', roman: 'onegaishimasu' },
    ],
    keywords: [
      { jp: 'ホテル', kana: 'ホテル', kr: '호텔', icon: '🏨' },
      { jp: 'まで', kana: 'まで', kr: '~까지', icon: '➡️' },
    ],
    categoryId: 'l1_transport',
    level: 1,
    order: 7,
    tip: '택시에서 목적지를 말할 때 ~までお願いします를 사용해요.',
  },
  {
    id: 'l1_transport_008',
    jp: '何時に着きますか？',
    kana: 'なんじにつきますか？',
    kr: '몇 시에 도착하나요?',
    roman: 'Nanji ni tsukimasu ka?',
    chunks: [
      { jp: '何時に', kana: 'なんじに', kr: '몇 시에', roman: 'nanji ni' },
      { jp: '着きますか', kana: 'つきますか', kr: '도착하나요', roman: 'tsukimasu ka' },
    ],
    keywords: [
      { jp: '何時', kana: 'なんじ', kr: '몇 시', icon: '🕐' },
      { jp: '着く', kana: 'つく', kr: '도착하다', icon: '🎯' },
    ],
    categoryId: 'l1_transport',
    level: 1,
    order: 8,
    tip: '着く(つく)는 "도착하다"라는 뜻이에요.',
  },
  {
    id: 'l1_transport_009',
    jp: 'ICカードにチャージしたいです。',
    kana: 'アイシーカードにチャージしたいです。',
    kr: 'IC카드 충전하고 싶어요.',
    roman: 'Aishii kaado ni chaaji shitai desu.',
    chunks: [
      { jp: 'ICカードに', kana: 'アイシーカードに', kr: 'IC카드에', roman: 'aishii kaado ni' },
      { jp: 'チャージ', kana: 'チャージ', kr: '충전', roman: 'chaaji' },
      { jp: 'したいです', kana: 'したいです', kr: '하고 싶어요', roman: 'shitai desu' },
    ],
    keywords: [
      { jp: 'ICカード', kana: 'アイシーカード', kr: 'IC카드', icon: '💳' },
      { jp: 'チャージ', kana: 'チャージ', kr: '충전', icon: '🔋' },
    ],
    categoryId: 'l1_transport',
    level: 1,
    order: 9,
    tip: 'Suica, Pasmo 등 IC카드는 편의점에서도 충전 가능해요.',
  },
  {
    id: 'l1_transport_010',
    jp: '終電は何時ですか？',
    kana: 'しゅうでんはなんじですか？',
    kr: '막차는 몇 시인가요?',
    roman: 'Shuuden wa nanji desu ka?',
    chunks: [
      { jp: '終電は', kana: 'しゅうでんは', kr: '막차는', roman: 'shuuden wa' },
      { jp: '何時ですか', kana: 'なんじですか', kr: '몇 시인가요', roman: 'nanji desu ka' },
    ],
    keywords: [
      { jp: '終電', kana: 'しゅうでん', kr: '막차', icon: '🌙' },
      { jp: '何時', kana: 'なんじ', kr: '몇 시', icon: '🕐' },
    ],
    categoryId: 'l1_transport',
    level: 1,
    order: 10,
    tip: '終電(しゅうでん)은 막차, 始発(しはつ)은 첫차예요.',
  },
] as const;
