import type { Sentence } from '../../types';

export const FOOD_SENTENCES: readonly Sentence[] = [
  {
    id: 'l2_food_001',
    jp: 'おすすめは何ですか？',
    kana: 'おすすめはなんですか？',
    kr: '추천 메뉴가 뭔가요?',
    roman: 'Osusume wa nan desu ka?',
    chunks: [
      { jp: 'おすすめは', kana: 'おすすめは', kr: '추천은', roman: 'osusume wa' },
      { jp: '何ですか', kana: 'なんですか', kr: '뭔가요', roman: 'nan desu ka' },
    ],
    keywords: [
      { jp: 'おすすめ', kana: 'おすすめ', kr: '추천', icon: '👍' },
      { jp: '人気', kana: 'にんき', kr: '인기', icon: '⭐' },
    ],
    categoryId: 'l2_food',
    level: 2,
    order: 1,
    tip: '식당에서 메뉴 고르기 어려울 때 유용한 표현이에요.',
  },
  {
    id: 'l2_food_002',
    jp: 'このラーメンは美味しいですね。',
    kana: 'このラーメンはおいしいですね。',
    kr: '이 라멘 맛있네요.',
    roman: 'Kono raamen wa oishii desu ne.',
    chunks: [
      { jp: 'この', kana: 'この', kr: '이', roman: 'kono' },
      { jp: 'ラーメンは', kana: 'ラーメンは', kr: '라멘은', roman: 'raamen wa' },
      { jp: '美味しいですね', kana: 'おいしいですね', kr: '맛있네요', roman: 'oishii desu ne' },
    ],
    keywords: [
      { jp: 'ラーメン', kana: 'ラーメン', kr: '라멘', icon: '🍜' },
      { jp: '美味しい', kana: 'おいしい', kr: '맛있다', icon: '😋' },
    ],
    categoryId: 'l2_food',
    level: 2,
    order: 2,
    tip: '음식 칭찬은 요리사나 가게 주인에게 좋은 인상을 줘요.',
  },
  {
    id: 'l2_food_003',
    jp: '寿司を食べたことがありますか？',
    kana: 'すしをたべたことがありますか？',
    kr: '초밥 먹어본 적 있어요?',
    roman: 'Sushi wo tabeta koto ga arimasu ka?',
    chunks: [
      { jp: '寿司を', kana: 'すしを', kr: '초밥을', roman: 'sushi wo' },
      { jp: '食べたことが', kana: 'たべたことが', kr: '먹어본 적이', roman: 'tabeta koto ga' },
      { jp: 'ありますか', kana: 'ありますか', kr: '있어요', roman: 'arimasu ka' },
    ],
    keywords: [
      { jp: '寿司', kana: 'すし', kr: '초밥', icon: '🍣' },
      { jp: '~たことがある', kana: '~たことがある', kr: '~한 적 있다', icon: '✓' },
    ],
    categoryId: 'l2_food',
    level: 2,
    order: 3,
    tip: '~たことがあります는 경험을 묻거나 말할 때 사용해요.',
  },
  {
    id: 'l2_food_004',
    jp: '辛いものは食べられますか？',
    kana: 'からいものはたべられますか？',
    kr: '매운 거 먹을 수 있어요?',
    roman: 'Karai mono wa taberaremasu ka?',
    chunks: [
      { jp: '辛いものは', kana: 'からいものは', kr: '매운 것은', roman: 'karai mono wa' },
      { jp: '食べられますか', kana: 'たべられますか', kr: '먹을 수 있어요', roman: 'taberaremasu ka' },
    ],
    keywords: [
      { jp: '辛い', kana: 'からい', kr: '맵다', icon: '🌶️' },
      { jp: '甘い', kana: 'あまい', kr: '달다', icon: '🍯' },
    ],
    categoryId: 'l2_food',
    level: 2,
    order: 4,
    tip: '맛 표현: 辛い(맵다), 甘い(달다), 苦い(쓰다), 酸っぱい(시다)',
  },
  {
    id: 'l2_food_005',
    jp: '韓国料理は好きですか？',
    kana: 'かんこくりょうりはすきですか？',
    kr: '한국 음식 좋아해요?',
    roman: 'Kankoku ryouri wa suki desu ka?',
    chunks: [
      { jp: '韓国料理は', kana: 'かんこくりょうりは', kr: '한국 요리는', roman: 'kankoku ryouri wa' },
      { jp: '好きですか', kana: 'すきですか', kr: '좋아해요', roman: 'suki desu ka' },
    ],
    keywords: [
      { jp: '韓国料理', kana: 'かんこくりょうり', kr: '한국 요리', icon: '🇰🇷' },
      { jp: '日本料理', kana: 'にほんりょうり', kr: '일본 요리', icon: '🇯🇵' },
    ],
    categoryId: 'l2_food',
    level: 2,
    order: 5,
    tip: '음식 이야기는 대화를 이어가기 좋은 주제예요.',
  },
  {
    id: 'l2_food_006',
    jp: 'お腹がいっぱいです。',
    kana: 'おなかがいっぱいです。',
    kr: '배불러요.',
    roman: 'Onaka ga ippai desu.',
    chunks: [
      { jp: 'お腹が', kana: 'おなかが', kr: '배가', roman: 'onaka ga' },
      { jp: 'いっぱいです', kana: 'いっぱいです', kr: '가득해요', roman: 'ippai desu' },
    ],
    keywords: [
      { jp: 'お腹', kana: 'おなか', kr: '배', icon: '🫃' },
      { jp: 'いっぱい', kana: 'いっぱい', kr: '가득', icon: '😊' },
    ],
    categoryId: 'l2_food',
    level: 2,
    order: 6,
    tip: '반대로 "배고파요"는 お腹が空きました예요.',
  },
  {
    id: 'l2_food_007',
    jp: 'ご馳走様でした。',
    kana: 'ごちそうさまでした。',
    kr: '잘 먹었습니다.',
    roman: 'Gochisousama deshita.',
    chunks: [
      { jp: 'ご馳走様', kana: 'ごちそうさま', kr: '잘 먹었습니다', roman: 'gochisousama' },
      { jp: 'でした', kana: 'でした', kr: '(과거)', roman: 'deshita' },
    ],
    keywords: [
      { jp: 'ご馳走様', kana: 'ごちそうさま', kr: '잘 먹었습니다', icon: '🙏' },
      { jp: 'いただきます', kana: 'いただきます', kr: '잘 먹겠습니다', icon: '🍽️' },
    ],
    categoryId: 'l2_food',
    level: 2,
    order: 7,
    tip: '식사 전 いただきます, 식사 후 ご馳走様でした가 기본이에요.',
  },
  {
    id: 'l2_food_008',
    jp: 'この店は行列ができていますね。',
    kana: 'このみせはぎょうれつができていますね。',
    kr: '이 가게는 줄이 서 있네요.',
    roman: 'Kono mise wa gyouretsu ga dekite imasu ne.',
    chunks: [
      { jp: 'この店は', kana: 'このみせは', kr: '이 가게는', roman: 'kono mise wa' },
      { jp: '行列が', kana: 'ぎょうれつが', kr: '줄이', roman: 'gyouretsu ga' },
      { jp: 'できていますね', kana: 'できていますね', kr: '서 있네요', roman: 'dekite imasu ne' },
    ],
    keywords: [
      { jp: '行列', kana: 'ぎょうれつ', kr: '줄', icon: '👥' },
      { jp: '店', kana: 'みせ', kr: '가게', icon: '🏪' },
    ],
    categoryId: 'l2_food',
    level: 2,
    order: 8,
    tip: '일본의 맛집은 줄 서서 먹는 문화가 있어요.',
  },
  {
    id: 'l2_food_009',
    jp: 'アレルギーがあります。',
    kana: 'アレルギーがあります。',
    kr: '알레르기가 있어요.',
    roman: 'Arerugii ga arimasu.',
    chunks: [
      { jp: 'アレルギーが', kana: 'アレルギーが', kr: '알레르기가', roman: 'arerugii ga' },
      { jp: 'あります', kana: 'あります', kr: '있어요', roman: 'arimasu' },
    ],
    keywords: [
      { jp: 'アレルギー', kana: 'アレルギー', kr: '알레르기', icon: '⚠️' },
      { jp: '卵', kana: 'たまご', kr: '계란', icon: '🥚' },
    ],
    categoryId: 'l2_food',
    level: 2,
    order: 9,
    tip: '卵(계란), 小麦(밀), 牛乳(우유) 등 알레르기 재료를 말해요.',
  },
  {
    id: 'l2_food_010',
    jp: 'もう一杯いかがですか？',
    kana: 'もういっぱいいかがですか？',
    kr: '한 잔 더 드실래요?',
    roman: 'Mou ippai ikaga desu ka?',
    chunks: [
      { jp: 'もう一杯', kana: 'もういっぱい', kr: '한 잔 더', roman: 'mou ippai' },
      { jp: 'いかがですか', kana: 'いかがですか', kr: '어떠세요', roman: 'ikaga desu ka' },
    ],
    keywords: [
      { jp: '一杯', kana: 'いっぱい', kr: '한 잔', icon: '🍺' },
      { jp: 'いかが', kana: 'いかが', kr: '어떠세요', icon: '❓' },
    ],
    categoryId: 'l2_food',
    level: 2,
    order: 10,
    tip: 'いかがですか는 どうですか보다 정중한 표현이에요.',
  },
] as const;
