import type { Sentence } from '../../types';

export const GREETING_SENTENCES: readonly Sentence[] = [
  {
    id: 'l2_greeting_001',
    jp: 'はじめまして、キムと申します。',
    kana: 'はじめまして、キムともうします。',
    kr: '처음 뵙겠습니다, 김이라고 합니다.',
    roman: 'Hajimemashite, Kimu to moushimasu.',
    chunks: [
      { jp: 'はじめまして', kana: 'はじめまして', kr: '처음 뵙겠습니다', roman: 'hajimemashite' },
      { jp: 'キムと', kana: 'キムと', kr: '김이라고', roman: 'Kimu to' },
      { jp: '申します', kana: 'もうします', kr: '합니다', roman: 'moushimasu' },
    ],
    keywords: [
      { jp: 'はじめまして', kana: 'はじめまして', kr: '처음 뵙겠습니다', icon: '👋' },
      { jp: '申す', kana: 'もうす', kr: '말씀드리다', icon: '🎤' },
    ],
    categoryId: 'l2_greeting',
    level: 2,
    order: 1,
    tip: '~と申します는 ~といいます보다 더 정중한 자기소개예요.',
  },
  {
    id: 'l2_greeting_002',
    jp: '韓国から来ました。',
    kana: 'かんこくからきました。',
    kr: '한국에서 왔습니다.',
    roman: 'Kankoku kara kimashita.',
    chunks: [
      { jp: '韓国から', kana: 'かんこくから', kr: '한국에서', roman: 'kankoku kara' },
      { jp: '来ました', kana: 'きました', kr: '왔습니다', roman: 'kimashita' },
    ],
    keywords: [
      { jp: '韓国', kana: 'かんこく', kr: '한국', icon: '🇰🇷' },
      { jp: '来る', kana: 'くる', kr: '오다', icon: '✈️' },
    ],
    categoryId: 'l2_greeting',
    level: 2,
    order: 2,
    tip: '~から来ました는 출신지를 말할 때 사용해요.',
  },
  {
    id: 'l2_greeting_003',
    jp: 'どうぞよろしくお願いします。',
    kana: 'どうぞよろしくおねがいします。',
    kr: '잘 부탁드립니다.',
    roman: 'Douzo yoroshiku onegaishimasu.',
    chunks: [
      { jp: 'どうぞ', kana: 'どうぞ', kr: '아무쪼록', roman: 'douzo' },
      { jp: 'よろしく', kana: 'よろしく', kr: '잘', roman: 'yoroshiku' },
      { jp: 'お願いします', kana: 'おねがいします', kr: '부탁드립니다', roman: 'onegaishimasu' },
    ],
    keywords: [
      { jp: 'よろしく', kana: 'よろしく', kr: '잘 부탁해', icon: '🤝' },
      { jp: 'どうぞ', kana: 'どうぞ', kr: '아무쪼록', icon: '🙏' },
    ],
    categoryId: 'l2_greeting',
    level: 2,
    order: 3,
    tip: '자기소개 마무리에 꼭 붙이는 인사말이에요.',
  },
  {
    id: 'l2_greeting_004',
    jp: 'お会いできて嬉しいです。',
    kana: 'おあいできてうれしいです。',
    kr: '만나서 반갑습니다.',
    roman: 'Oai dekite ureshii desu.',
    chunks: [
      { jp: 'お会いできて', kana: 'おあいできて', kr: '만날 수 있어서', roman: 'oai dekite' },
      { jp: '嬉しいです', kana: 'うれしいです', kr: '기뻐요', roman: 'ureshii desu' },
    ],
    keywords: [
      { jp: '会う', kana: 'あう', kr: '만나다', icon: '🤝' },
      { jp: '嬉しい', kana: 'うれしい', kr: '기쁘다', icon: '😊' },
    ],
    categoryId: 'l2_greeting',
    level: 2,
    order: 4,
    tip: '영어의 "Nice to meet you"와 같은 뉘앙스예요.',
  },
  {
    id: 'l2_greeting_005',
    jp: 'お久しぶりです。',
    kana: 'おひさしぶりです。',
    kr: '오랜만이에요.',
    roman: 'Ohisashiburi desu.',
    chunks: [
      { jp: 'お久しぶり', kana: 'おひさしぶり', kr: '오랜만', roman: 'ohisashiburi' },
      { jp: 'です', kana: 'です', kr: '이에요', roman: 'desu' },
    ],
    keywords: [
      { jp: '久しぶり', kana: 'ひさしぶり', kr: '오랜만', icon: '👋' },
      { jp: 'お元気ですか', kana: 'おげんきですか', kr: '잘 지내셨어요?', icon: '💪' },
    ],
    categoryId: 'l2_greeting',
    level: 2,
    order: 5,
    tip: '친한 사이에는 久しぶり!라고만 해도 돼요.',
  },
  {
    id: 'l2_greeting_006',
    jp: 'お元気でしたか？',
    kana: 'おげんきでしたか？',
    kr: '잘 지내셨어요?',
    roman: 'Ogenki deshita ka?',
    chunks: [
      { jp: 'お元気', kana: 'おげんき', kr: '건강', roman: 'ogenki' },
      { jp: 'でしたか', kana: 'でしたか', kr: '이었나요', roman: 'deshita ka' },
    ],
    keywords: [
      { jp: '元気', kana: 'げんき', kr: '건강/기운', icon: '💪' },
      { jp: 'おかげさまで', kana: 'おかげさまで', kr: '덕분에', icon: '🙏' },
    ],
    categoryId: 'l2_greeting',
    level: 2,
    order: 6,
    tip: '대답은 "おかげさまで、元気です"가 자연스러워요.',
  },
  {
    id: 'l2_greeting_007',
    jp: '今日はありがとうございました。',
    kana: 'きょうはありがとうございました。',
    kr: '오늘 감사했습니다.',
    roman: 'Kyou wa arigatou gozaimashita.',
    chunks: [
      { jp: '今日は', kana: 'きょうは', kr: '오늘은', roman: 'kyou wa' },
      { jp: 'ありがとう', kana: 'ありがとう', kr: '감사', roman: 'arigatou' },
      { jp: 'ございました', kana: 'ございました', kr: '했습니다', roman: 'gozaimashita' },
    ],
    keywords: [
      { jp: '今日', kana: 'きょう', kr: '오늘', icon: '📅' },
      { jp: 'ありがとう', kana: 'ありがとう', kr: '고마워', icon: '🙏' },
    ],
    categoryId: 'l2_greeting',
    level: 2,
    order: 7,
    tip: '헤어질 때 그 날 있었던 일에 감사를 표하는 인사예요.',
  },
  {
    id: 'l2_greeting_008',
    jp: 'またお会いしましょう。',
    kana: 'またおあいしましょう。',
    kr: '또 만나요.',
    roman: 'Mata oai shimashou.',
    chunks: [
      { jp: 'また', kana: 'また', kr: '또', roman: 'mata' },
      { jp: 'お会いしましょう', kana: 'おあいしましょう', kr: '만나요', roman: 'oai shimashou' },
    ],
    keywords: [
      { jp: 'また', kana: 'また', kr: '또/다시', icon: '🔄' },
      { jp: '会う', kana: 'あう', kr: '만나다', icon: '👥' },
    ],
    categoryId: 'l2_greeting',
    level: 2,
    order: 8,
    tip: '~ましょう는 "~합시다"로 제안하는 표현이에요.',
  },
  {
    id: 'l2_greeting_009',
    jp: 'お先に失礼します。',
    kana: 'おさきにしつれいします。',
    kr: '먼저 실례하겠습니다.',
    roman: 'Osaki ni shitsurei shimasu.',
    chunks: [
      { jp: 'お先に', kana: 'おさきに', kr: '먼저', roman: 'osaki ni' },
      { jp: '失礼します', kana: 'しつれいします', kr: '실례합니다', roman: 'shitsurei shimasu' },
    ],
    keywords: [
      { jp: 'お先に', kana: 'おさきに', kr: '먼저', icon: '👋' },
      { jp: '失礼', kana: 'しつれい', kr: '실례', icon: '🚪' },
    ],
    categoryId: 'l2_greeting',
    level: 2,
    order: 9,
    tip: '직장이나 모임에서 먼저 나갈 때 사용하는 인사예요.',
  },
  {
    id: 'l2_greeting_010',
    jp: '気をつけてお帰りください。',
    kana: 'きをつけておかえりください。',
    kr: '조심해서 돌아가세요.',
    roman: 'Ki wo tsukete okaeri kudasai.',
    chunks: [
      { jp: '気をつけて', kana: 'きをつけて', kr: '조심해서', roman: 'ki wo tsukete' },
      { jp: 'お帰りください', kana: 'おかえりください', kr: '돌아가세요', roman: 'okaeri kudasai' },
    ],
    keywords: [
      { jp: '気をつける', kana: 'きをつける', kr: '조심하다', icon: '⚠️' },
      { jp: '帰る', kana: 'かえる', kr: '돌아가다', icon: '🏠' },
    ],
    categoryId: 'l2_greeting',
    level: 2,
    order: 10,
    tip: '손님이나 친구를 배웅할 때 하는 인사예요.',
  },
] as const;
