import type { Sentence } from '../../types';

export const HOBBY_SENTENCES: readonly Sentence[] = [
  {
    id: 'l2_hobby_001',
    jp: '趣味は何ですか？',
    kana: 'しゅみはなんですか？',
    kr: '취미가 뭐예요?',
    roman: 'Shumi wa nan desu ka?',
    chunks: [
      { jp: '趣味は', kana: 'しゅみは', kr: '취미는', roman: 'shumi wa' },
      { jp: '何ですか', kana: 'なんですか', kr: '뭐예요', roman: 'nan desu ka' },
    ],
    keywords: [
      { jp: '趣味', kana: 'しゅみ', kr: '취미', icon: '🎯' },
      { jp: '何', kana: 'なに/なん', kr: '무엇', icon: '❓' },
    ],
    categoryId: 'l2_hobby',
    level: 2,
    order: 1,
    tip: '스몰토크에서 가장 흔한 질문 중 하나예요.',
  },
  {
    id: 'l2_hobby_002',
    jp: '趣味は映画を見ることです。',
    kana: 'しゅみはえいがをみることです。',
    kr: '취미는 영화 보는 거예요.',
    roman: 'Shumi wa eiga wo miru koto desu.',
    chunks: [
      { jp: '趣味は', kana: 'しゅみは', kr: '취미는', roman: 'shumi wa' },
      { jp: '映画を', kana: 'えいがを', kr: '영화를', roman: 'eiga wo' },
      { jp: '見ること', kana: 'みること', kr: '보는 것', roman: 'miru koto' },
      { jp: 'です', kana: 'です', kr: '이에요', roman: 'desu' },
    ],
    keywords: [
      { jp: '映画', kana: 'えいが', kr: '영화', icon: '🎬' },
      { jp: '~こと', kana: '~こと', kr: '~하는 것', icon: '📝' },
    ],
    categoryId: 'l2_hobby',
    level: 2,
    order: 2,
    tip: '동사 + こと는 "~하는 것"으로 명사화해요.',
  },
  {
    id: 'l2_hobby_003',
    jp: '最近ゲームにハマっています。',
    kana: 'さいきんゲームにハマっています。',
    kr: '요즘 게임에 빠져있어요.',
    roman: 'Saikin geemu ni hamatte imasu.',
    chunks: [
      { jp: '最近', kana: 'さいきん', kr: '요즘', roman: 'saikin' },
      { jp: 'ゲームに', kana: 'ゲームに', kr: '게임에', roman: 'geemu ni' },
      { jp: 'ハマっています', kana: 'ハマっています', kr: '빠져있어요', roman: 'hamatte imasu' },
    ],
    keywords: [
      { jp: '最近', kana: 'さいきん', kr: '요즘', icon: '🕐' },
      { jp: 'ハマる', kana: 'ハマる', kr: '빠지다', icon: '🎮' },
    ],
    categoryId: 'l2_hobby',
    level: 2,
    order: 3,
    tip: 'ハマる는 무언가에 푹 빠지다라는 뜻의 구어체예요.',
  },
  {
    id: 'l2_hobby_004',
    jp: '休みの日は何をしていますか？',
    kana: 'やすみのひはなにをしていますか？',
    kr: '쉬는 날에는 뭐 해요?',
    roman: 'Yasumi no hi wa nani wo shite imasu ka?',
    chunks: [
      { jp: '休みの日は', kana: 'やすみのひは', kr: '쉬는 날에는', roman: 'yasumi no hi wa' },
      { jp: '何を', kana: 'なにを', kr: '무엇을', roman: 'nani wo' },
      { jp: 'していますか', kana: 'していますか', kr: '하고 있어요', roman: 'shite imasu ka' },
    ],
    keywords: [
      { jp: '休み', kana: 'やすみ', kr: '휴일', icon: '🏖️' },
      { jp: '~の日', kana: '~のひ', kr: '~하는 날', icon: '📅' },
    ],
    categoryId: 'l2_hobby',
    level: 2,
    order: 4,
    tip: '주말 계획이나 휴일 활동을 물을 때 사용해요.',
  },
  {
    id: 'l2_hobby_005',
    jp: '音楽を聴くのが好きです。',
    kana: 'おんがくをきくのがすきです。',
    kr: '음악 듣는 걸 좋아해요.',
    roman: 'Ongaku wo kiku no ga suki desu.',
    chunks: [
      { jp: '音楽を', kana: 'おんがくを', kr: '음악을', roman: 'ongaku wo' },
      { jp: '聴くのが', kana: 'きくのが', kr: '듣는 게', roman: 'kiku no ga' },
      { jp: '好きです', kana: 'すきです', kr: '좋아해요', roman: 'suki desu' },
    ],
    keywords: [
      { jp: '音楽', kana: 'おんがく', kr: '음악', icon: '🎵' },
      { jp: '聴く', kana: 'きく', kr: '듣다', icon: '🎧' },
    ],
    categoryId: 'l2_hobby',
    level: 2,
    order: 5,
    tip: '동사 + のが好き는 "~하는 것을 좋아하다"예요.',
  },
  {
    id: 'l2_hobby_006',
    jp: '週末はよく料理をします。',
    kana: 'しゅうまつはよくりょうりをします。',
    kr: '주말에는 자주 요리해요.',
    roman: 'Shuumatsu wa yoku ryouri wo shimasu.',
    chunks: [
      { jp: '週末は', kana: 'しゅうまつは', kr: '주말에는', roman: 'shuumatsu wa' },
      { jp: 'よく', kana: 'よく', kr: '자주', roman: 'yoku' },
      { jp: '料理をします', kana: 'りょうりをします', kr: '요리해요', roman: 'ryouri wo shimasu' },
    ],
    keywords: [
      { jp: '週末', kana: 'しゅうまつ', kr: '주말', icon: '📆' },
      { jp: '料理', kana: 'りょうり', kr: '요리', icon: '🍳' },
    ],
    categoryId: 'l2_hobby',
    level: 2,
    order: 6,
    tip: 'よく는 "자주", "잘"이라는 뜻으로 빈도를 나타내요.',
  },
  {
    id: 'l2_hobby_007',
    jp: '日本のアニメが好きです。',
    kana: 'にほんのアニメがすきです。',
    kr: '일본 애니메이션을 좋아해요.',
    roman: 'Nihon no anime ga suki desu.',
    chunks: [
      { jp: '日本の', kana: 'にほんの', kr: '일본의', roman: 'nihon no' },
      { jp: 'アニメが', kana: 'アニメが', kr: '애니메이션이', roman: 'anime ga' },
      { jp: '好きです', kana: 'すきです', kr: '좋아해요', roman: 'suki desu' },
    ],
    keywords: [
      { jp: 'アニメ', kana: 'アニメ', kr: '애니메이션', icon: '📺' },
      { jp: '漫画', kana: 'まんが', kr: '만화', icon: '📚' },
    ],
    categoryId: 'l2_hobby',
    level: 2,
    order: 7,
    tip: '일본인과 대화할 때 공통 관심사로 좋은 주제예요.',
  },
  {
    id: 'l2_hobby_008',
    jp: '運動は苦手です。',
    kana: 'うんどうはにがてです。',
    kr: '운동은 잘 못해요.',
    roman: 'Undou wa nigate desu.',
    chunks: [
      { jp: '運動は', kana: 'うんどうは', kr: '운동은', roman: 'undou wa' },
      { jp: '苦手です', kana: 'にがてです', kr: '잘 못해요', roman: 'nigate desu' },
    ],
    keywords: [
      { jp: '運動', kana: 'うんどう', kr: '운동', icon: '🏃' },
      { jp: '苦手', kana: 'にがて', kr: '잘 못하는', icon: '😅' },
    ],
    categoryId: 'l2_hobby',
    level: 2,
    order: 8,
    tip: '苦手(にがて)는 잘 못하거나 싫어하는 것을 말해요.',
  },
  {
    id: 'l2_hobby_009',
    jp: '一緒にカラオケに行きませんか？',
    kana: 'いっしょにカラオケにいきませんか？',
    kr: '같이 노래방 갈래요?',
    roman: 'Issho ni karaoke ni ikimasen ka?',
    chunks: [
      { jp: '一緒に', kana: 'いっしょに', kr: '같이', roman: 'issho ni' },
      { jp: 'カラオケに', kana: 'カラオケに', kr: '노래방에', roman: 'karaoke ni' },
      { jp: '行きませんか', kana: 'いきませんか', kr: '가지 않을래요', roman: 'ikimasen ka' },
    ],
    keywords: [
      { jp: '一緒に', kana: 'いっしょに', kr: '같이', icon: '👥' },
      { jp: 'カラオケ', kana: 'カラオケ', kr: '노래방', icon: '🎤' },
    ],
    categoryId: 'l2_hobby',
    level: 2,
    order: 9,
    tip: '~ませんか?는 부드럽게 권유하는 표현이에요.',
  },
  {
    id: 'l2_hobby_010',
    jp: '写真を撮るのが趣味です。',
    kana: 'しゃしんをとるのがしゅみです。',
    kr: '사진 찍는 게 취미예요.',
    roman: 'Shashin wo toru no ga shumi desu.',
    chunks: [
      { jp: '写真を', kana: 'しゃしんを', kr: '사진을', roman: 'shashin wo' },
      { jp: '撮るのが', kana: 'とるのが', kr: '찍는 게', roman: 'toru no ga' },
      { jp: '趣味です', kana: 'しゅみです', kr: '취미예요', roman: 'shumi desu' },
    ],
    keywords: [
      { jp: '写真', kana: 'しゃしん', kr: '사진', icon: '📷' },
      { jp: '撮る', kana: 'とる', kr: '찍다', icon: '📸' },
    ],
    categoryId: 'l2_hobby',
    level: 2,
    order: 10,
    tip: '여행 중 사진 찍기 좋아한다고 하면 대화가 잘 이어져요.',
  },
] as const;
