import type { Sentence } from '../../types';

export const WEATHER_SENTENCES: readonly Sentence[] = [
  {
    id: 'l2_weather_001',
    jp: '今日はいい天気ですね。',
    kana: 'きょうはいいてんきですね。',
    kr: '오늘 날씨 좋네요.',
    roman: 'Kyou wa ii tenki desu ne.',
    chunks: [
      { jp: '今日は', kana: 'きょうは', kr: '오늘은', roman: 'kyou wa' },
      { jp: 'いい天気', kana: 'いいてんき', kr: '좋은 날씨', roman: 'ii tenki' },
      { jp: 'ですね', kana: 'ですね', kr: '네요', roman: 'desu ne' },
    ],
    keywords: [
      { jp: '天気', kana: 'てんき', kr: '날씨', icon: '🌤️' },
      { jp: 'いい', kana: 'いい', kr: '좋다', icon: '👍' },
    ],
    categoryId: 'l2_weather',
    level: 2,
    order: 1,
    tip: '~ですね는 동의를 구하거나 공감할 때 사용해요.',
  },
  {
    id: 'l2_weather_002',
    jp: '今日は暑いですね。',
    kana: 'きょうはあついですね。',
    kr: '오늘 덥네요.',
    roman: 'Kyou wa atsui desu ne.',
    chunks: [
      { jp: '今日は', kana: 'きょうは', kr: '오늘은', roman: 'kyou wa' },
      { jp: '暑いですね', kana: 'あついですね', kr: '덥네요', roman: 'atsui desu ne' },
    ],
    keywords: [
      { jp: '暑い', kana: 'あつい', kr: '덥다', icon: '🥵' },
      { jp: '寒い', kana: 'さむい', kr: '춥다', icon: '🥶' },
    ],
    categoryId: 'l2_weather',
    level: 2,
    order: 2,
    tip: '暑い(あつい)는 덥다, 寒い(さむい)는 춥다예요.',
  },
  {
    id: 'l2_weather_003',
    jp: '明日は雨が降りそうですね。',
    kana: 'あしたはあめがふりそうですね。',
    kr: '내일은 비가 올 것 같네요.',
    roman: 'Ashita wa ame ga furisou desu ne.',
    chunks: [
      { jp: '明日は', kana: 'あしたは', kr: '내일은', roman: 'ashita wa' },
      { jp: '雨が', kana: 'あめが', kr: '비가', roman: 'ame ga' },
      { jp: '降りそうですね', kana: 'ふりそうですね', kr: '올 것 같네요', roman: 'furisou desu ne' },
    ],
    keywords: [
      { jp: '雨', kana: 'あめ', kr: '비', icon: '🌧️' },
      { jp: '降る', kana: 'ふる', kr: '내리다', icon: '💧' },
    ],
    categoryId: 'l2_weather',
    level: 2,
    order: 3,
    tip: '~そうです는 "~할 것 같다"로 추측을 나타내요.',
  },
  {
    id: 'l2_weather_004',
    jp: '桜の季節が好きです。',
    kana: 'さくらのきせつがすきです。',
    kr: '벚꽃 계절을 좋아해요.',
    roman: 'Sakura no kisetsu ga suki desu.',
    chunks: [
      { jp: '桜の', kana: 'さくらの', kr: '벚꽃의', roman: 'sakura no' },
      { jp: '季節が', kana: 'きせつが', kr: '계절이', roman: 'kisetsu ga' },
      { jp: '好きです', kana: 'すきです', kr: '좋아해요', roman: 'suki desu' },
    ],
    keywords: [
      { jp: '桜', kana: 'さくら', kr: '벚꽃', icon: '🌸' },
      { jp: '季節', kana: 'きせつ', kr: '계절', icon: '🗓️' },
    ],
    categoryId: 'l2_weather',
    level: 2,
    order: 4,
    tip: '일본의 벚꽃 시즌은 3월 말~4월 초예요.',
  },
  {
    id: 'l2_weather_005',
    jp: '紅葉がきれいですね。',
    kana: 'こうようがきれいですね。',
    kr: '단풍이 예쁘네요.',
    roman: 'Kouyou ga kirei desu ne.',
    chunks: [
      { jp: '紅葉が', kana: 'こうようが', kr: '단풍이', roman: 'kouyou ga' },
      { jp: 'きれいですね', kana: 'きれいですね', kr: '예쁘네요', roman: 'kirei desu ne' },
    ],
    keywords: [
      { jp: '紅葉', kana: 'こうよう', kr: '단풍', icon: '🍁' },
      { jp: 'きれい', kana: 'きれい', kr: '예쁘다', icon: '✨' },
    ],
    categoryId: 'l2_weather',
    level: 2,
    order: 5,
    tip: '일본의 단풍 시즌은 10월~11월이에요.',
  },
  {
    id: 'l2_weather_006',
    jp: '涼しくなりましたね。',
    kana: 'すずしくなりましたね。',
    kr: '시원해졌네요.',
    roman: 'Suzushiku narimashita ne.',
    chunks: [
      { jp: '涼しく', kana: 'すずしく', kr: '시원하게', roman: 'suzushiku' },
      { jp: 'なりましたね', kana: 'なりましたね', kr: '되었네요', roman: 'narimashita ne' },
    ],
    keywords: [
      { jp: '涼しい', kana: 'すずしい', kr: '시원하다', icon: '🍃' },
      { jp: '暖かい', kana: 'あたたかい', kr: '따뜻하다', icon: '☀️' },
    ],
    categoryId: 'l2_weather',
    level: 2,
    order: 6,
    tip: '~くなりました는 "~해졌다"로 변화를 나타내요.',
  },
  {
    id: 'l2_weather_007',
    jp: '雪が降っていますね。',
    kana: 'ゆきがふっていますね。',
    kr: '눈이 내리고 있네요.',
    roman: 'Yuki ga futte imasu ne.',
    chunks: [
      { jp: '雪が', kana: 'ゆきが', kr: '눈이', roman: 'yuki ga' },
      { jp: '降っています', kana: 'ふっています', kr: '내리고 있어요', roman: 'futte imasu' },
    ],
    keywords: [
      { jp: '雪', kana: 'ゆき', kr: '눈', icon: '❄️' },
      { jp: '~ている', kana: '~ている', kr: '~하고 있다', icon: '⏳' },
    ],
    categoryId: 'l2_weather',
    level: 2,
    order: 7,
    tip: '~ています는 진행 중인 상태를 나타내요.',
  },
  {
    id: 'l2_weather_008',
    jp: '日本の夏は蒸し暑いですね。',
    kana: 'にほんのなつはむしあついですね。',
    kr: '일본 여름은 무덥네요.',
    roman: 'Nihon no natsu wa mushiatsui desu ne.',
    chunks: [
      { jp: '日本の夏は', kana: 'にほんのなつは', kr: '일본의 여름은', roman: 'nihon no natsu wa' },
      { jp: '蒸し暑いですね', kana: 'むしあついですね', kr: '무덥네요', roman: 'mushiatsui desu ne' },
    ],
    keywords: [
      { jp: '夏', kana: 'なつ', kr: '여름', icon: '☀️' },
      { jp: '蒸し暑い', kana: 'むしあつい', kr: '무덥다', icon: '💦' },
    ],
    categoryId: 'l2_weather',
    level: 2,
    order: 8,
    tip: '蒸し暑い(むしあつい)는 습하고 더운 것을 말해요.',
  },
  {
    id: 'l2_weather_009',
    jp: '台風が来るみたいですね。',
    kana: 'たいふうがくるみたいですね。',
    kr: '태풍이 오는 것 같네요.',
    roman: 'Taifuu ga kuru mitai desu ne.',
    chunks: [
      { jp: '台風が', kana: 'たいふうが', kr: '태풍이', roman: 'taifuu ga' },
      { jp: '来る', kana: 'くる', kr: '오다', roman: 'kuru' },
      { jp: 'みたいですね', kana: 'みたいですね', kr: '것 같네요', roman: 'mitai desu ne' },
    ],
    keywords: [
      { jp: '台風', kana: 'たいふう', kr: '태풍', icon: '🌀' },
      { jp: '~みたい', kana: '~みたい', kr: '~같다', icon: '🤔' },
    ],
    categoryId: 'l2_weather',
    level: 2,
    order: 9,
    tip: '~みたいです는 "~같아요"로 추측이나 비유를 나타내요.',
  },
  {
    id: 'l2_weather_010',
    jp: '今日は風が強いですね。',
    kana: 'きょうはかぜがつよいですね。',
    kr: '오늘은 바람이 세네요.',
    roman: 'Kyou wa kaze ga tsuyoi desu ne.',
    chunks: [
      { jp: '今日は', kana: 'きょうは', kr: '오늘은', roman: 'kyou wa' },
      { jp: '風が', kana: 'かぜが', kr: '바람이', roman: 'kaze ga' },
      { jp: '強いですね', kana: 'つよいですね', kr: '세네요', roman: 'tsuyoi desu ne' },
    ],
    keywords: [
      { jp: '風', kana: 'かぜ', kr: '바람', icon: '💨' },
      { jp: '強い', kana: 'つよい', kr: '강하다', icon: '💪' },
    ],
    categoryId: 'l2_weather',
    level: 2,
    order: 10,
    tip: '강도를 나타낼 때: 強い(강하다) ↔ 弱い(약하다)',
  },
] as const;
