import type { Sentence } from '../../types';

export const ADVANCED_SENTENCES: readonly Sentence[] = [
  {
    id: 'l3_advanced_001',
    jp: 'ちょっと日本っぽいですね。',
    kana: 'ちょっとにほんっぽいですね。',
    kr: '좀 일본스럽네요.',
    roman: 'Chotto nihon ppoi desu ne.',
    chunks: [
      { jp: 'ちょっと', kana: 'ちょっと', kr: '좀', roman: 'chotto' },
      { jp: '日本っぽい', kana: 'にほんっぽい', kr: '일본스럽다', roman: 'nihon ppoi' },
      { jp: 'ですね', kana: 'ですね', kr: '네요', roman: 'desu ne' },
    ],
    keywords: [
      { jp: '~っぽい', kana: '~っぽい', kr: '~스럽다', icon: '🎨' },
      { jp: '日本', kana: 'にほん', kr: '일본', icon: '🇯🇵' },
    ],
    categoryId: 'l3_advanced',
    level: 3,
    order: 1,
    tip: '~っぽい는 "~같다, ~스럽다"로 특징을 표현해요.',
  },
  {
    id: 'l3_advanced_002',
    jp: '別にそういうわけじゃないです。',
    kana: 'べつにそういうわけじゃないです。',
    kr: '딱히 그런 건 아니에요.',
    roman: 'Betsu ni sou iu wake ja nai desu.',
    chunks: [
      { jp: '別に', kana: 'べつに', kr: '딱히', roman: 'betsu ni' },
      { jp: 'そういうわけ', kana: 'そういうわけ', kr: '그런 이유', roman: 'sou iu wake' },
      { jp: 'じゃないです', kana: 'じゃないです', kr: '가 아니에요', roman: 'ja nai desu' },
    ],
    keywords: [
      { jp: '別に', kana: 'べつに', kr: '딱히', icon: '🤷' },
      { jp: 'わけではない', kana: 'わけではない', kr: '~인 것은 아니다', icon: '❌' },
    ],
    categoryId: 'l3_advanced',
    level: 3,
    order: 2,
    tip: '~わけではない는 부분 부정으로 뉘앙스를 조절해요.',
  },
  {
    id: 'l3_advanced_003',
    jp: '今日は早めに帰ることにします。',
    kana: 'きょうははやめにかえることにします。',
    kr: '오늘은 일찍 가기로 할게요.',
    roman: 'Kyou wa hayame ni kaeru koto ni shimasu.',
    chunks: [
      { jp: '今日は', kana: 'きょうは', kr: '오늘은', roman: 'kyou wa' },
      { jp: '早めに', kana: 'はやめに', kr: '일찍', roman: 'hayame ni' },
      { jp: '帰ることにします', kana: 'かえることにします', kr: '가기로 할게요', roman: 'kaeru koto ni shimasu' },
    ],
    keywords: [
      { jp: '早め', kana: 'はやめ', kr: '일찍/빨리', icon: '⏰' },
      { jp: '~ことにする', kana: '~ことにする', kr: '~하기로 하다', icon: '✅' },
    ],
    categoryId: 'l3_advanced',
    level: 3,
    order: 3,
    tip: '~ことにする는 스스로 결정했음을 나타내요.',
  },
  {
    id: 'l3_advanced_004',
    jp: '雨が降りそうなので傘を持ってきました。',
    kana: 'あめがふりそうなのでかさをもってきました。',
    kr: '비가 올 것 같아서 우산을 가져왔어요.',
    roman: 'Ame ga furisou na no de kasa wo motte kimashita.',
    chunks: [
      { jp: '雨が降りそうなので', kana: 'あめがふりそうなので', kr: '비가 올 것 같아서', roman: 'ame ga furisou na no de' },
      { jp: '傘を', kana: 'かさを', kr: '우산을', roman: 'kasa wo' },
      { jp: '持ってきました', kana: 'もってきました', kr: '가져왔어요', roman: 'motte kimashita' },
    ],
    keywords: [
      { jp: '~そう', kana: '~そう', kr: '~할 것 같다', icon: '🤔' },
      { jp: '~ので', kana: '~ので', kr: '~해서', icon: '➡️' },
    ],
    categoryId: 'l3_advanced',
    level: 3,
    order: 4,
    tip: '~そうなので는 추측의 이유를 말할 때 사용해요.',
  },
  {
    id: 'l3_advanced_005',
    jp: 'せっかくだから食べてみよう。',
    kana: 'せっかくだからたべてみよう。',
    kr: '모처럼이니까 먹어보자.',
    roman: 'Sekkaku da kara tabete miyou.',
    chunks: [
      { jp: 'せっかくだから', kana: 'せっかくだから', kr: '모처럼이니까', roman: 'sekkaku da kara' },
      { jp: '食べてみよう', kana: 'たべてみよう', kr: '먹어보자', roman: 'tabete miyou' },
    ],
    keywords: [
      { jp: 'せっかく', kana: 'せっかく', kr: '모처럼', icon: '✨' },
      { jp: '~てみる', kana: '~てみる', kr: '~해보다', icon: '👀' },
    ],
    categoryId: 'l3_advanced',
    level: 3,
    order: 5,
    tip: 'せっかく는 기회나 노력을 아깝게 여기는 뉘앙스예요.',
  },
  {
    id: 'l3_advanced_006',
    jp: 'やっぱりそうだったんですね。',
    kana: 'やっぱりそうだったんですね。',
    kr: '역시 그랬군요.',
    roman: 'Yappari sou dattan desu ne.',
    chunks: [
      { jp: 'やっぱり', kana: 'やっぱり', kr: '역시', roman: 'yappari' },
      { jp: 'そうだったんですね', kana: 'そうだったんですね', kr: '그랬군요', roman: 'sou dattan desu ne' },
    ],
    keywords: [
      { jp: 'やっぱり', kana: 'やっぱり', kr: '역시/아무래도', icon: '💡' },
      { jp: '~んですね', kana: '~んですね', kr: '~군요', icon: '😮' },
    ],
    categoryId: 'l3_advanced',
    level: 3,
    order: 6,
    tip: 'やっぱり는 예상이 맞았을 때 사용해요.',
  },
  {
    id: 'l3_advanced_007',
    jp: 'なんとなくわかります。',
    kana: 'なんとなくわかります。',
    kr: '왠지 알 것 같아요.',
    roman: 'Nantonaku wakarimasu.',
    chunks: [
      { jp: 'なんとなく', kana: 'なんとなく', kr: '왠지', roman: 'nantonaku' },
      { jp: 'わかります', kana: 'わかります', kr: '알 것 같아요', roman: 'wakarimasu' },
    ],
    keywords: [
      { jp: 'なんとなく', kana: 'なんとなく', kr: '왠지/어쩐지', icon: '🤔' },
      { jp: 'わかる', kana: 'わかる', kr: '알다', icon: '💡' },
    ],
    categoryId: 'l3_advanced',
    level: 3,
    order: 7,
    tip: 'なんとなく는 명확한 이유 없이 느껴지는 것을 표현해요.',
  },
  {
    id: 'l3_advanced_008',
    jp: 'どうりで美味しいと思った。',
    kana: 'どうりでおいしいとおもった。',
    kr: '어쩐지 맛있더라니.',
    roman: 'Douri de oishii to omotta.',
    chunks: [
      { jp: 'どうりで', kana: 'どうりで', kr: '어쩐지', roman: 'douri de' },
      { jp: '美味しいと', kana: 'おいしいと', kr: '맛있다고', roman: 'oishii to' },
      { jp: '思った', kana: 'おもった', kr: '생각했다', roman: 'omotta' },
    ],
    keywords: [
      { jp: 'どうりで', kana: 'どうりで', kr: '어쩐지/그래서', icon: '💡' },
      { jp: '~と思った', kana: '~とおもった', kr: '~라고 생각했다', icon: '💭' },
    ],
    categoryId: 'l3_advanced',
    level: 3,
    order: 8,
    tip: 'どうりで는 이유를 알고 납득할 때 사용해요.',
  },
  {
    id: 'l3_advanced_009',
    jp: 'さすがですね。',
    kana: 'さすがですね。',
    kr: '역시 대단하시네요.',
    roman: 'Sasuga desu ne.',
    chunks: [
      { jp: 'さすが', kana: 'さすが', kr: '역시', roman: 'sasuga' },
      { jp: 'ですね', kana: 'ですね', kr: '네요', roman: 'desu ne' },
    ],
    keywords: [
      { jp: 'さすが', kana: 'さすが', kr: '역시/과연', icon: '👏' },
      { jp: '流石', kana: 'さすが', kr: '역시(한자)', icon: '⭐' },
    ],
    categoryId: 'l3_advanced',
    level: 3,
    order: 9,
    tip: 'さすが는 기대대로일 때 감탄하며 칭찬하는 표현이에요.',
  },
  {
    id: 'l3_advanced_010',
    jp: '一応確認しておきます。',
    kana: 'いちおうかくにんしておきます。',
    kr: '일단 확인해 둘게요.',
    roman: 'Ichiou kakunin shite okimasu.',
    chunks: [
      { jp: '一応', kana: 'いちおう', kr: '일단', roman: 'ichiou' },
      { jp: '確認して', kana: 'かくにんして', kr: '확인하고', roman: 'kakunin shite' },
      { jp: 'おきます', kana: 'おきます', kr: '둘게요', roman: 'okimasu' },
    ],
    keywords: [
      { jp: '一応', kana: 'いちおう', kr: '일단/일응', icon: '📝' },
      { jp: '~ておく', kana: '~ておく', kr: '~해 두다', icon: '✅' },
    ],
    categoryId: 'l3_advanced',
    level: 3,
    order: 10,
    tip: '~ておく는 미리 준비하거나 해두는 것을 나타내요.',
  },
] as const;
