import type { Sentence } from '../../types';

export const BUSINESS_SENTENCES: readonly Sentence[] = [
  {
    id: 'l3_business_001',
    jp: 'お忙しいところ恐れ入ります。',
    kana: 'おいそがしいところおそれいります。',
    kr: '바쁘신 와중에 죄송합니다.',
    roman: 'Oisogashii tokoro osore irimasu.',
    chunks: [
      { jp: 'お忙しいところ', kana: 'おいそがしいところ', kr: '바쁘신 와중에', roman: 'oisogashii tokoro' },
      { jp: '恐れ入ります', kana: 'おそれいります', kr: '죄송합니다', roman: 'osore irimasu' },
    ],
    keywords: [
      { jp: '忙しい', kana: 'いそがしい', kr: '바쁘다', icon: '⏰' },
      { jp: '恐れ入る', kana: 'おそれいる', kr: '죄송하다(겸양)', icon: '🙇' },
    ],
    categoryId: 'l3_business',
    level: 3,
    order: 1,
    tip: '비즈니스에서 부탁이나 질문 전에 쓰는 정중한 서두예요.',
  },
  {
    id: 'l3_business_002',
    jp: 'ご確認いただけますか？',
    kana: 'ごかくにんいただけますか？',
    kr: '확인해 주실 수 있으신가요?',
    roman: 'Gokakunin itadakemasu ka?',
    chunks: [
      { jp: 'ご確認', kana: 'ごかくにん', kr: '확인', roman: 'gokakunin' },
      { jp: 'いただけますか', kana: 'いただけますか', kr: '해 주실 수 있나요', roman: 'itadakemasu ka' },
    ],
    keywords: [
      { jp: '確認', kana: 'かくにん', kr: '확인', icon: '✅' },
      { jp: 'いただく', kana: 'いただく', kr: '받다(겸양)', icon: '🙏' },
    ],
    categoryId: 'l3_business',
    level: 3,
    order: 2,
    tip: '~いただけますか는 정중하게 부탁할 때 사용하는 표현이에요.',
  },
  {
    id: 'l3_business_003',
    jp: '少々お待ちください。',
    kana: 'しょうしょうおまちください。',
    kr: '잠시만 기다려 주세요.',
    roman: 'Shoushou omachi kudasai.',
    chunks: [
      { jp: '少々', kana: 'しょうしょう', kr: '잠시', roman: 'shoushou' },
      { jp: 'お待ちください', kana: 'おまちください', kr: '기다려 주세요', roman: 'omachi kudasai' },
    ],
    keywords: [
      { jp: '少々', kana: 'しょうしょう', kr: '잠시', icon: '⏳' },
      { jp: 'お待ちください', kana: 'おまちください', kr: '기다려 주세요', icon: '🙏' },
    ],
    categoryId: 'l3_business',
    level: 3,
    order: 3,
    tip: '少々는 ちょっと의 정중한 표현이에요.',
  },
  {
    id: 'l3_business_004',
    jp: '担当者に確認いたします。',
    kana: 'たんとうしゃにかくにんいたします。',
    kr: '담당자에게 확인하겠습니다.',
    roman: 'Tantousha ni kakunin itashimasu.',
    chunks: [
      { jp: '担当者に', kana: 'たんとうしゃに', kr: '담당자에게', roman: 'tantousha ni' },
      { jp: '確認', kana: 'かくにん', kr: '확인', roman: 'kakunin' },
      { jp: 'いたします', kana: 'いたします', kr: '하겠습니다', roman: 'itashimasu' },
    ],
    keywords: [
      { jp: '担当者', kana: 'たんとうしゃ', kr: '담당자', icon: '👔' },
      { jp: 'いたす', kana: 'いたす', kr: '하다(겸양)', icon: '🙇' },
    ],
    categoryId: 'l3_business',
    level: 3,
    order: 4,
    tip: 'いたします는 します의 겸양어로 비즈니스에서 자주 써요.',
  },
  {
    id: 'l3_business_005',
    jp: '後ほどご連絡いたします。',
    kana: 'のちほどごれんらくいたします。',
    kr: '나중에 연락드리겠습니다.',
    roman: 'Nochihodo gorenraku itashimasu.',
    chunks: [
      { jp: '後ほど', kana: 'のちほど', kr: '나중에', roman: 'nochihodo' },
      { jp: 'ご連絡', kana: 'ごれんらく', kr: '연락', roman: 'gorenraku' },
      { jp: 'いたします', kana: 'いたします', kr: '드리겠습니다', roman: 'itashimasu' },
    ],
    keywords: [
      { jp: '後ほど', kana: 'のちほど', kr: '나중에', icon: '🕐' },
      { jp: '連絡', kana: 'れんらく', kr: '연락', icon: '📞' },
    ],
    categoryId: 'l3_business',
    level: 3,
    order: 5,
    tip: '後ほど는 後で의 정중한 표현이에요.',
  },
  {
    id: 'l3_business_006',
    jp: 'お手数をおかけしますが。',
    kana: 'おてすうをおかけしますが。',
    kr: '번거로우시겠지만.',
    roman: 'Otesuu wo okake shimasu ga.',
    chunks: [
      { jp: 'お手数を', kana: 'おてすうを', kr: '수고를', roman: 'otesuu wo' },
      { jp: 'おかけしますが', kana: 'おかけしますが', kr: '끼치겠지만', roman: 'okake shimasu ga' },
    ],
    keywords: [
      { jp: 'お手数', kana: 'おてすう', kr: '수고', icon: '🙇' },
      { jp: 'おかけする', kana: 'おかけする', kr: '끼치다', icon: '🤲' },
    ],
    categoryId: 'l3_business',
    level: 3,
    order: 6,
    tip: '부탁할 때 상대방의 수고에 미리 사과하는 표현이에요.',
  },
  {
    id: 'l3_business_007',
    jp: '検討させていただきます。',
    kana: 'けんとうさせていただきます。',
    kr: '검토하겠습니다.',
    roman: 'Kentou sasete itadakimasu.',
    chunks: [
      { jp: '検討', kana: 'けんとう', kr: '검토', roman: 'kentou' },
      { jp: 'させていただきます', kana: 'させていただきます', kr: '하겠습니다', roman: 'sasete itadakimasu' },
    ],
    keywords: [
      { jp: '検討', kana: 'けんとう', kr: '검토', icon: '🔍' },
      { jp: '~させていただく', kana: '~させていただく', kr: '~하겠습니다(겸양)', icon: '🙏' },
    ],
    categoryId: 'l3_business',
    level: 3,
    order: 7,
    tip: '~させていただきます는 허락을 구하며 하겠다는 겸양 표현이에요.',
  },
  {
    id: 'l3_business_008',
    jp: 'ご都合はいかがでしょうか？',
    kana: 'ごつごうはいかがでしょうか？',
    kr: '일정은 어떠신가요?',
    roman: 'Gotsugou wa ikaga deshou ka?',
    chunks: [
      { jp: 'ご都合は', kana: 'ごつごうは', kr: '일정은', roman: 'gotsugou wa' },
      { jp: 'いかがでしょうか', kana: 'いかがでしょうか', kr: '어떠신가요', roman: 'ikaga deshou ka' },
    ],
    keywords: [
      { jp: '都合', kana: 'つごう', kr: '일정/사정', icon: '📅' },
      { jp: 'いかが', kana: 'いかが', kr: '어떠세요', icon: '❓' },
    ],
    categoryId: 'l3_business',
    level: 3,
    order: 8,
    tip: '미팅 일정을 잡을 때 자주 사용하는 표현이에요.',
  },
  {
    id: 'l3_business_009',
    jp: 'よろしくお伝えください。',
    kana: 'よろしくおつたえください。',
    kr: '안부 전해 주세요.',
    roman: 'Yoroshiku otsutae kudasai.',
    chunks: [
      { jp: 'よろしく', kana: 'よろしく', kr: '잘', roman: 'yoroshiku' },
      { jp: 'お伝えください', kana: 'おつたえください', kr: '전해 주세요', roman: 'otsutae kudasai' },
    ],
    keywords: [
      { jp: '伝える', kana: 'つたえる', kr: '전하다', icon: '📨' },
      { jp: 'よろしく', kana: 'よろしく', kr: '잘 부탁해', icon: '🤝' },
    ],
    categoryId: 'l3_business',
    level: 3,
    order: 9,
    tip: '부재중인 사람에게 안부를 전해달라고 할 때 사용해요.',
  },
  {
    id: 'l3_business_010',
    jp: '本日はありがとうございました。',
    kana: 'ほんじつはありがとうございました。',
    kr: '오늘 감사했습니다.',
    roman: 'Honjitsu wa arigatou gozaimashita.',
    chunks: [
      { jp: '本日は', kana: 'ほんじつは', kr: '오늘은', roman: 'honjitsu wa' },
      { jp: 'ありがとうございました', kana: 'ありがとうございました', kr: '감사했습니다', roman: 'arigatou gozaimashita' },
    ],
    keywords: [
      { jp: '本日', kana: 'ほんじつ', kr: '오늘', icon: '📅' },
      { jp: 'ありがとうございました', kana: 'ありがとうございました', kr: '감사했습니다', icon: '🙏' },
    ],
    categoryId: 'l3_business',
    level: 3,
    order: 10,
    tip: '本日는 今日의 정중한 표현으로 비즈니스에서 자주 써요.',
  },
] as const;
