import type { Sentence } from '../../types';

export const CULTURE_SENTENCES: readonly Sentence[] = [
  {
    id: 'l3_culture_001',
    jp: '靴を脱いでください。',
    kana: 'くつをぬいでください。',
    kr: '신발을 벗어주세요.',
    roman: 'Kutsu wo nuide kudasai.',
    chunks: [
      { jp: '靴を', kana: 'くつを', kr: '신발을', roman: 'kutsu wo' },
      { jp: '脱いでください', kana: 'ぬいでください', kr: '벗어주세요', roman: 'nuide kudasai' },
    ],
    keywords: [
      { jp: '靴', kana: 'くつ', kr: '신발', icon: '👟' },
      { jp: '脱ぐ', kana: 'ぬぐ', kr: '벗다', icon: '🚪' },
    ],
    categoryId: 'l3_culture',
    level: 3,
    order: 1,
    tip: '일본 가정이나 전통 료칸에서는 신발을 벗는 것이 예의예요.',
  },
  {
    id: 'l3_culture_002',
    jp: 'お箸の使い方が上手ですね。',
    kana: 'おはしのつかいかたがじょうずですね。',
    kr: '젓가락질 잘하시네요.',
    roman: 'Ohashi no tsukaikata ga jouzu desu ne.',
    chunks: [
      { jp: 'お箸の', kana: 'おはしの', kr: '젓가락의', roman: 'ohashi no' },
      { jp: '使い方が', kana: 'つかいかたが', kr: '사용법이', roman: 'tsukaikata ga' },
      { jp: '上手ですね', kana: 'じょうずですね', kr: '능숙하네요', roman: 'jouzu desu ne' },
    ],
    keywords: [
      { jp: '箸', kana: 'はし', kr: '젓가락', icon: '🥢' },
      { jp: '上手', kana: 'じょうず', kr: '능숙하다', icon: '👏' },
    ],
    categoryId: 'l3_culture',
    level: 3,
    order: 2,
    tip: '외국인에게 자주 하는 칭찬이에요. 겸손하게 いいえ라고 대답해요.',
  },
  {
    id: 'l3_culture_003',
    jp: 'お邪魔します。',
    kana: 'おじゃまします。',
    kr: '실례합니다. (남의 집에 들어갈 때)',
    roman: 'Ojama shimasu.',
    chunks: [
      { jp: 'お邪魔', kana: 'おじゃま', kr: '방해', roman: 'ojama' },
      { jp: 'します', kana: 'します', kr: '합니다', roman: 'shimasu' },
    ],
    keywords: [
      { jp: 'お邪魔', kana: 'おじゃま', kr: '방해', icon: '🚪' },
      { jp: 'お邪魔しました', kana: 'おじゃましました', kr: '실례했습니다(나갈 때)', icon: '👋' },
    ],
    categoryId: 'l3_culture',
    level: 3,
    order: 3,
    tip: '들어갈 때 お邪魔します, 나갈 때 お邪魔しました를 써요.',
  },
  {
    id: 'l3_culture_004',
    jp: 'つまらないものですが。',
    kana: 'つまらないものですが。',
    kr: '변변치 않은 것입니다만.',
    roman: 'Tsumaranai mono desu ga.',
    chunks: [
      { jp: 'つまらない', kana: 'つまらない', kr: '변변찮은', roman: 'tsumaranai' },
      { jp: 'ものですが', kana: 'ものですが', kr: '것입니다만', roman: 'mono desu ga' },
    ],
    keywords: [
      { jp: 'つまらない', kana: 'つまらない', kr: '변변찮다', icon: '🎁' },
      { jp: 'もの', kana: 'もの', kr: '것/물건', icon: '📦' },
    ],
    categoryId: 'l3_culture',
    level: 3,
    order: 4,
    tip: '선물을 줄 때 겸손하게 말하는 전통적인 표현이에요.',
  },
  {
    id: 'l3_culture_005',
    jp: '遠慮なくいただきます。',
    kana: 'えんりょなくいただきます。',
    kr: '사양 않고 받겠습니다.',
    roman: 'Enryo naku itadakimasu.',
    chunks: [
      { jp: '遠慮なく', kana: 'えんりょなく', kr: '사양 않고', roman: 'enryo naku' },
      { jp: 'いただきます', kana: 'いただきます', kr: '받겠습니다', roman: 'itadakimasu' },
    ],
    keywords: [
      { jp: '遠慮', kana: 'えんりょ', kr: '사양/겸손', icon: '🙇' },
      { jp: 'いただく', kana: 'いただく', kr: '받다(겸양)', icon: '🙏' },
    ],
    categoryId: 'l3_culture',
    level: 3,
    order: 5,
    tip: '음식이나 선물을 권유받았을 때 감사히 받겠다는 표현이에요.',
  },
  {
    id: 'l3_culture_006',
    jp: '乾杯！',
    kana: 'かんぱい！',
    kr: '건배!',
    roman: 'Kanpai!',
    chunks: [
      { jp: '乾杯', kana: 'かんぱい', kr: '건배', roman: 'kanpai' },
    ],
    keywords: [
      { jp: '乾杯', kana: 'かんぱい', kr: '건배', icon: '🍻' },
      { jp: 'お疲れ様', kana: 'おつかれさま', kr: '수고하셨습니다', icon: '🍺' },
    ],
    categoryId: 'l3_culture',
    level: 3,
    order: 6,
    tip: '일본에서는 乾杯 전에 마시기 시작하면 예의에 어긋나요.',
  },
  {
    id: 'l3_culture_007',
    jp: '失礼ですが、おいくつですか？',
    kana: 'しつれいですが、おいくつですか？',
    kr: '실례지만, 연세가 어떻게 되세요?',
    roman: 'Shitsurei desu ga, oikutsu desu ka?',
    chunks: [
      { jp: '失礼ですが', kana: 'しつれいですが', kr: '실례지만', roman: 'shitsurei desu ga' },
      { jp: 'おいくつですか', kana: 'おいくつですか', kr: '연세가 어떻게 되세요', roman: 'oikutsu desu ka' },
    ],
    keywords: [
      { jp: '失礼', kana: 'しつれい', kr: '실례', icon: '🙇' },
      { jp: 'おいくつ', kana: 'おいくつ', kr: '연세', icon: '🎂' },
    ],
    categoryId: 'l3_culture',
    level: 3,
    order: 7,
    tip: '나이를 묻기 전에 失礼ですが를 붙이면 정중해요.',
  },
  {
    id: 'l3_culture_008',
    jp: 'お先にどうぞ。',
    kana: 'おさきにどうぞ。',
    kr: '먼저 하세요.',
    roman: 'Osaki ni douzo.',
    chunks: [
      { jp: 'お先に', kana: 'おさきに', kr: '먼저', roman: 'osaki ni' },
      { jp: 'どうぞ', kana: 'どうぞ', kr: '하세요', roman: 'douzo' },
    ],
    keywords: [
      { jp: 'お先に', kana: 'おさきに', kr: '먼저', icon: '🚶' },
      { jp: 'どうぞ', kana: 'どうぞ', kr: '어서', icon: '🙌' },
    ],
    categoryId: 'l3_culture',
    level: 3,
    order: 8,
    tip: '엘리베이터나 문에서 양보할 때 사용하는 표현이에요.',
  },
  {
    id: 'l3_culture_009',
    jp: 'おかげさまで。',
    kana: 'おかげさまで。',
    kr: '덕분에요.',
    roman: 'Okagesamade.',
    chunks: [
      { jp: 'おかげさまで', kana: 'おかげさまで', kr: '덕분에', roman: 'okagesamade' },
    ],
    keywords: [
      { jp: 'おかげさま', kana: 'おかげさま', kr: '덕분', icon: '🙏' },
      { jp: 'おかげで', kana: 'おかげで', kr: '덕분에', icon: '✨' },
    ],
    categoryId: 'l3_culture',
    level: 3,
    order: 9,
    tip: '"어떻게 지내세요?"에 대한 겸손한 대답으로 자주 써요.',
  },
  {
    id: 'l3_culture_010',
    jp: 'お気をつけて。',
    kana: 'おきをつけて。',
    kr: '조심하세요.',
    roman: 'Oki wo tsukete.',
    chunks: [
      { jp: 'お気をつけて', kana: 'おきをつけて', kr: '조심하세요', roman: 'oki wo tsukete' },
    ],
    keywords: [
      { jp: '気をつける', kana: 'きをつける', kr: '조심하다', icon: '⚠️' },
      { jp: 'お体に気をつけて', kana: 'おからだにきをつけて', kr: '건강 조심하세요', icon: '💪' },
    ],
    categoryId: 'l3_culture',
    level: 3,
    order: 10,
    tip: '헤어질 때 상대방의 안전을 빌어주는 인사예요.',
  },
] as const;
