import type { Sentence } from '../../types';

export const EMOTION_SENTENCES: readonly Sentence[] = [
  {
    id: 'l3_emotion_001',
    jp: '来てよかったです。',
    kana: 'きてよかったです。',
    kr: '와서 다행이에요.',
    roman: 'Kite yokatta desu.',
    chunks: [
      { jp: '来て', kana: 'きて', kr: '와서', roman: 'kite' },
      { jp: 'よかったです', kana: 'よかったです', kr: '다행이에요', roman: 'yokatta desu' },
    ],
    keywords: [
      { jp: 'よかった', kana: 'よかった', kr: '다행이다/좋았다', icon: '😊' },
      { jp: '~てよかった', kana: '~てよかった', kr: '~해서 다행이다', icon: '✨' },
    ],
    categoryId: 'l3_emotion',
    level: 3,
    order: 1,
    tip: '~てよかった는 "~해서 다행이다/좋았다"라는 만족감을 표현해요.',
  },
  {
    id: 'l3_emotion_002',
    jp: 'それは大変でしたね。',
    kana: 'それはたいへんでしたね。',
    kr: '그거 힘드셨겠네요.',
    roman: 'Sore wa taihen deshita ne.',
    chunks: [
      { jp: 'それは', kana: 'それは', kr: '그것은', roman: 'sore wa' },
      { jp: '大変でしたね', kana: 'たいへんでしたね', kr: '힘드셨겠네요', roman: 'taihen deshita ne' },
    ],
    keywords: [
      { jp: '大変', kana: 'たいへん', kr: '힘들다', icon: '😰' },
      { jp: '~でしたね', kana: '~でしたね', kr: '~였네요', icon: '🤝' },
    ],
    categoryId: 'l3_emotion',
    level: 3,
    order: 2,
    tip: '상대방의 힘든 경험에 공감할 때 사용하는 표현이에요.',
  },
  {
    id: 'l3_emotion_003',
    jp: 'すごく嬉しかったです。',
    kana: 'すごくうれしかったです。',
    kr: '정말 기뻤어요.',
    roman: 'Sugoku ureshikatta desu.',
    chunks: [
      { jp: 'すごく', kana: 'すごく', kr: '정말', roman: 'sugoku' },
      { jp: '嬉しかったです', kana: 'うれしかったです', kr: '기뻤어요', roman: 'ureshikatta desu' },
    ],
    keywords: [
      { jp: 'すごく', kana: 'すごく', kr: '매우/정말', icon: '⭐' },
      { jp: '嬉しい', kana: 'うれしい', kr: '기쁘다', icon: '😄' },
    ],
    categoryId: 'l3_emotion',
    level: 3,
    order: 3,
    tip: 'すごく는 とても보다 구어체에서 자주 쓰이는 강조 표현이에요.',
  },
  {
    id: 'l3_emotion_004',
    jp: 'ちょっと寂しいですね。',
    kana: 'ちょっとさびしいですね。',
    kr: '좀 쓸쓸하네요.',
    roman: 'Chotto sabishii desu ne.',
    chunks: [
      { jp: 'ちょっと', kana: 'ちょっと', kr: '좀', roman: 'chotto' },
      { jp: '寂しいですね', kana: 'さびしいですね', kr: '쓸쓸하네요', roman: 'sabishii desu ne' },
    ],
    keywords: [
      { jp: '寂しい', kana: 'さびしい', kr: '쓸쓸하다', icon: '😢' },
      { jp: 'ちょっと', kana: 'ちょっと', kr: '조금', icon: '🤏' },
    ],
    categoryId: 'l3_emotion',
    level: 3,
    order: 4,
    tip: 'ちょっと를 붙이면 감정 표현이 부드러워져요.',
  },
  {
    id: 'l3_emotion_005',
    jp: '心配しないでください。',
    kana: 'しんぱいしないでください。',
    kr: '걱정하지 마세요.',
    roman: 'Shinpai shinaide kudasai.',
    chunks: [
      { jp: '心配', kana: 'しんぱい', kr: '걱정', roman: 'shinpai' },
      { jp: 'しないで', kana: 'しないで', kr: '하지 말고', roman: 'shinaide' },
      { jp: 'ください', kana: 'ください', kr: '주세요', roman: 'kudasai' },
    ],
    keywords: [
      { jp: '心配', kana: 'しんぱい', kr: '걱정', icon: '😟' },
      { jp: '~ないでください', kana: '~ないでください', kr: '~하지 마세요', icon: '🚫' },
    ],
    categoryId: 'l3_emotion',
    level: 3,
    order: 5,
    tip: '~ないでください는 정중하게 하지 말라고 부탁하는 표현이에요.',
  },
  {
    id: 'l3_emotion_006',
    jp: '感動しました。',
    kana: 'かんどうしました。',
    kr: '감동받았어요.',
    roman: 'Kandou shimashita.',
    chunks: [
      { jp: '感動', kana: 'かんどう', kr: '감동', roman: 'kandou' },
      { jp: 'しました', kana: 'しました', kr: '했어요', roman: 'shimashita' },
    ],
    keywords: [
      { jp: '感動', kana: 'かんどう', kr: '감동', icon: '🥹' },
      { jp: '感動する', kana: 'かんどうする', kr: '감동하다', icon: '✨' },
    ],
    categoryId: 'l3_emotion',
    level: 3,
    order: 6,
    tip: '영화, 공연, 경치 등에 감동받았을 때 사용해요.',
  },
  {
    id: 'l3_emotion_007',
    jp: 'わくわくしています。',
    kana: 'わくわくしています。',
    kr: '두근두근해요.',
    roman: 'Wakuwaku shite imasu.',
    chunks: [
      { jp: 'わくわく', kana: 'わくわく', kr: '두근두근', roman: 'wakuwaku' },
      { jp: 'しています', kana: 'しています', kr: '하고 있어요', roman: 'shite imasu' },
    ],
    keywords: [
      { jp: 'わくわく', kana: 'わくわく', kr: '두근두근', icon: '💓' },
      { jp: 'どきどき', kana: 'どきどき', kr: '두근두근(긴장)', icon: '💗' },
    ],
    categoryId: 'l3_emotion',
    level: 3,
    order: 7,
    tip: 'わくわく는 설렘, どきどき는 긴장이나 두려움 포함한 두근거림이에요.',
  },
  {
    id: 'l3_emotion_008',
    jp: 'ほっとしました。',
    kana: 'ほっとしました。',
    kr: '안심했어요.',
    roman: 'Hotto shimashita.',
    chunks: [
      { jp: 'ほっと', kana: 'ほっと', kr: '안심', roman: 'hotto' },
      { jp: 'しました', kana: 'しました', kr: '했어요', roman: 'shimashita' },
    ],
    keywords: [
      { jp: 'ほっとする', kana: 'ほっとする', kr: '안심하다', icon: '😌' },
      { jp: '安心', kana: 'あんしん', kr: '안심', icon: '😮‍💨' },
    ],
    categoryId: 'l3_emotion',
    level: 3,
    order: 8,
    tip: 'ほっと는 긴장이 풀리며 안도하는 느낌을 표현해요.',
  },
  {
    id: 'l3_emotion_009',
    jp: '懐かしいですね。',
    kana: 'なつかしいですね。',
    kr: '그립네요.',
    roman: 'Natsukashii desu ne.',
    chunks: [
      { jp: '懐かしい', kana: 'なつかしい', kr: '그립다', roman: 'natsukashii' },
      { jp: 'ですね', kana: 'ですね', kr: '네요', roman: 'desu ne' },
    ],
    keywords: [
      { jp: '懐かしい', kana: 'なつかしい', kr: '그립다/추억이다', icon: '🥲' },
      { jp: '思い出', kana: 'おもいで', kr: '추억', icon: '📷' },
    ],
    categoryId: 'l3_emotion',
    level: 3,
    order: 9,
    tip: '過去의 좋은 기억을 떠올릴 때 사용하는 감정 표현이에요.',
  },
  {
    id: 'l3_emotion_010',
    jp: 'びっくりしました。',
    kana: 'びっくりしました。',
    kr: '깜짝 놀랐어요.',
    roman: 'Bikkuri shimashita.',
    chunks: [
      { jp: 'びっくり', kana: 'びっくり', kr: '깜짝', roman: 'bikkuri' },
      { jp: 'しました', kana: 'しました', kr: '했어요', roman: 'shimashita' },
    ],
    keywords: [
      { jp: 'びっくり', kana: 'びっくり', kr: '깜짝', icon: '😲' },
      { jp: '驚く', kana: 'おどろく', kr: '놀라다', icon: '❗' },
    ],
    categoryId: 'l3_emotion',
    level: 3,
    order: 10,
    tip: 'びっくり는 구어체, 驚く(おどろく)는 문어체로 같은 의미예요.',
  },
] as const;
