import type { Sentence } from '../../types';

export const OPINION_SENTENCES: readonly Sentence[] = [
  {
    id: 'l3_opinion_001',
    jp: '私はそう思います。',
    kana: 'わたしはそうおもいます。',
    kr: '저는 그렇게 생각해요.',
    roman: 'Watashi wa sou omoimasu.',
    chunks: [
      { jp: '私は', kana: 'わたしは', kr: '저는', roman: 'watashi wa' },
      { jp: 'そう', kana: 'そう', kr: '그렇게', roman: 'sou' },
      { jp: '思います', kana: 'おもいます', kr: '생각해요', roman: 'omoimasu' },
    ],
    keywords: [
      { jp: '思う', kana: 'おもう', kr: '생각하다', icon: '💭' },
      { jp: 'そう', kana: 'そう', kr: '그렇게', icon: '👆' },
    ],
    categoryId: 'l3_opinion',
    level: 3,
    order: 1,
    tip: '~と思います는 의견을 말할 때 가장 기본적인 표현이에요.',
  },
  {
    id: 'l3_opinion_002',
    jp: 'そうかもしれませんね。',
    kana: 'そうかもしれませんね。',
    kr: '그럴지도 모르겠네요.',
    roman: 'Sou kamoshiremasen ne.',
    chunks: [
      { jp: 'そう', kana: 'そう', kr: '그렇게', roman: 'sou' },
      { jp: 'かもしれません', kana: 'かもしれません', kr: '일지도 몰라요', roman: 'kamoshiremasen' },
      { jp: 'ね', kana: 'ね', kr: '네', roman: 'ne' },
    ],
    keywords: [
      { jp: 'かもしれない', kana: 'かもしれない', kr: '~일지도 모르다', icon: '🤔' },
      { jp: '多分', kana: 'たぶん', kr: '아마', icon: '❓' },
    ],
    categoryId: 'l3_opinion',
    level: 3,
    order: 2,
    tip: '~かもしれません는 불확실한 추측을 나타내요.',
  },
  {
    id: 'l3_opinion_003',
    jp: '確かにそうですね。',
    kana: 'たしかにそうですね。',
    kr: '확실히 그렇네요.',
    roman: 'Tashika ni sou desu ne.',
    chunks: [
      { jp: '確かに', kana: 'たしかに', kr: '확실히', roman: 'tashika ni' },
      { jp: 'そうですね', kana: 'そうですね', kr: '그렇네요', roman: 'sou desu ne' },
    ],
    keywords: [
      { jp: '確かに', kana: 'たしかに', kr: '확실히', icon: '✅' },
      { jp: 'そうですね', kana: 'そうですね', kr: '그렇네요', icon: '🤝' },
    ],
    categoryId: 'l3_opinion',
    level: 3,
    order: 3,
    tip: '상대방 의견에 동의할 때 자주 쓰는 표현이에요.',
  },
  {
    id: 'l3_opinion_004',
    jp: 'ちょっと違うと思います。',
    kana: 'ちょっとちがうとおもいます。',
    kr: '좀 다르다고 생각해요.',
    roman: 'Chotto chigau to omoimasu.',
    chunks: [
      { jp: 'ちょっと', kana: 'ちょっと', kr: '좀', roman: 'chotto' },
      { jp: '違うと', kana: 'ちがうと', kr: '다르다고', roman: 'chigau to' },
      { jp: '思います', kana: 'おもいます', kr: '생각해요', roman: 'omoimasu' },
    ],
    keywords: [
      { jp: '違う', kana: 'ちがう', kr: '다르다', icon: '❌' },
      { jp: 'ちょっと', kana: 'ちょっと', kr: '조금', icon: '🤏' },
    ],
    categoryId: 'l3_opinion',
    level: 3,
    order: 4,
    tip: '직접 반대하지 않고 부드럽게 다른 의견을 말하는 방법이에요.',
  },
  {
    id: 'l3_opinion_005',
    jp: 'どちらとも言えないですね。',
    kana: 'どちらともいえないですね。',
    kr: '어느 쪽이라고 말하기 어렵네요.',
    roman: 'Dochira to mo ienai desu ne.',
    chunks: [
      { jp: 'どちらとも', kana: 'どちらとも', kr: '어느 쪽이라고도', roman: 'dochira to mo' },
      { jp: '言えない', kana: 'いえない', kr: '말할 수 없다', roman: 'ienai' },
      { jp: 'ですね', kana: 'ですね', kr: '네요', roman: 'desu ne' },
    ],
    keywords: [
      { jp: 'どちら', kana: 'どちら', kr: '어느 쪽', icon: '⚖️' },
      { jp: '言えない', kana: 'いえない', kr: '말할 수 없다', icon: '🤐' },
    ],
    categoryId: 'l3_opinion',
    level: 3,
    order: 5,
    tip: '중립적인 입장을 표현할 때 사용해요.',
  },
  {
    id: 'l3_opinion_006',
    jp: '個人的には賛成です。',
    kana: 'こじんてきにはさんせいです。',
    kr: '개인적으로는 찬성이에요.',
    roman: 'Kojinteki ni wa sansei desu.',
    chunks: [
      { jp: '個人的には', kana: 'こじんてきには', kr: '개인적으로는', roman: 'kojinteki ni wa' },
      { jp: '賛成です', kana: 'さんせいです', kr: '찬성이에요', roman: 'sansei desu' },
    ],
    keywords: [
      { jp: '個人的', kana: 'こじんてき', kr: '개인적', icon: '👤' },
      { jp: '賛成', kana: 'さんせい', kr: '찬성', icon: '👍' },
    ],
    categoryId: 'l3_opinion',
    level: 3,
    order: 6,
    tip: '반대는 反対(はんたい)예요. 개인 의견임을 강조할 때 사용해요.',
  },
  {
    id: 'l3_opinion_007',
    jp: 'なるほど、そういうことですか。',
    kana: 'なるほど、そういうことですか。',
    kr: '아하, 그런 거군요.',
    roman: 'Naruhodo, sou iu koto desu ka.',
    chunks: [
      { jp: 'なるほど', kana: 'なるほど', kr: '아하/그렇구나', roman: 'naruhodo' },
      { jp: 'そういうことですか', kana: 'そういうことですか', kr: '그런 거군요', roman: 'sou iu koto desu ka' },
    ],
    keywords: [
      { jp: 'なるほど', kana: 'なるほど', kr: '아하/그렇구나', icon: '💡' },
      { jp: 'そういうこと', kana: 'そういうこと', kr: '그런 것', icon: '🎯' },
    ],
    categoryId: 'l3_opinion',
    level: 3,
    order: 7,
    tip: '상대방의 설명을 이해했을 때 사용하는 표현이에요.',
  },
  {
    id: 'l3_opinion_008',
    jp: 'それはいい考えですね。',
    kana: 'それはいいかんがえですね。',
    kr: '그거 좋은 생각이네요.',
    roman: 'Sore wa ii kangae desu ne.',
    chunks: [
      { jp: 'それは', kana: 'それは', kr: '그것은', roman: 'sore wa' },
      { jp: 'いい考え', kana: 'いいかんがえ', kr: '좋은 생각', roman: 'ii kangae' },
      { jp: 'ですね', kana: 'ですね', kr: '이네요', roman: 'desu ne' },
    ],
    keywords: [
      { jp: '考え', kana: 'かんがえ', kr: '생각', icon: '💭' },
      { jp: 'いい', kana: 'いい', kr: '좋다', icon: '👍' },
    ],
    categoryId: 'l3_opinion',
    level: 3,
    order: 8,
    tip: '상대방의 아이디어나 제안에 긍정적으로 반응하는 표현이에요.',
  },
  {
    id: 'l3_opinion_009',
    jp: '私の意見を言ってもいいですか？',
    kana: 'わたしのいけんをいってもいいですか？',
    kr: '제 의견을 말해도 될까요?',
    roman: 'Watashi no iken wo itte mo ii desu ka?',
    chunks: [
      { jp: '私の意見を', kana: 'わたしのいけんを', kr: '제 의견을', roman: 'watashi no iken wo' },
      { jp: '言っても', kana: 'いっても', kr: '말해도', roman: 'itte mo' },
      { jp: 'いいですか', kana: 'いいですか', kr: '될까요', roman: 'ii desu ka' },
    ],
    keywords: [
      { jp: '意見', kana: 'いけん', kr: '의견', icon: '💬' },
      { jp: '~てもいい', kana: '~てもいい', kr: '~해도 되다', icon: '✅' },
    ],
    categoryId: 'l3_opinion',
    level: 3,
    order: 9,
    tip: '의견을 말하기 전에 허락을 구하는 정중한 표현이에요.',
  },
  {
    id: 'l3_opinion_010',
    jp: 'おっしゃる通りです。',
    kana: 'おっしゃるとおりです。',
    kr: '말씀하신 대로예요.',
    roman: 'Ossharu toori desu.',
    chunks: [
      { jp: 'おっしゃる', kana: 'おっしゃる', kr: '말씀하시다', roman: 'ossharu' },
      { jp: '通りです', kana: 'とおりです', kr: '대로예요', roman: 'toori desu' },
    ],
    keywords: [
      { jp: 'おっしゃる', kana: 'おっしゃる', kr: '말씀하시다(존경어)', icon: '👑' },
      { jp: '~通り', kana: '~とおり', kr: '~대로', icon: '➡️' },
    ],
    categoryId: 'l3_opinion',
    level: 3,
    order: 10,
    tip: 'おっしゃる는 言う의 존경어로 윗사람에게 사용해요.',
  },
] as const;
